### ISSUE TITLE
Failed Keplr multisig transaction

### ISSUE THREAD

**Issue by An0rak21** [chainapsis/keplr-wallet#1030]
Hi,

We created a community multisig to test the Keplr multisig.

We created a multisig with 19 addresses and 15 signatures to validate transactions without any warning about a maximum number of signatures.

On the first staking transaction, the following error message is displayed:

No wallet launch and no transaction possible.

**Screenshots**
![Capture d'écran 2024-01-19 132154](https://github.com/chainapsis/keplr-wallet/assets/141356985/b6a62165-58fe-40af-983e-1320c784b746)

**Device details (please complete the following information):**
 - OS: Windows
 - Browser: Brave v1.61.120
 - Keplr Version: 0.12.62

**Comment by An0rak21** [comment]
Correction we have 29 addresses (not 19) and 15 signatures to validate transactions

**Comment by Ryz0nd** [comment]
Hi @An0rak21,

Thank you for bringing this to our attention. We've recently learned that the cosmos-sdk only supports a maximum of 7 multisignatures. Consequently, the multisig with 15 signatures won't function as expected.

Due to this limitation, we are unable to process transactions from the mentioned account. To address this issue, we'd like to refund approximately 22 ATOM tokens. Could you please provide the receiving address for the refund?

**Comment by Ryz0nd** [comment]
Hi @An0rak21,

Thank you for bringing this to our attention. We've recently learned that the cosmos-sdk only supports a maximum of 7 multisignatures. Consequently, the multisig with 15 signatures won't function as expected.

We regret to inform you that transactions cannot be processed from the mentioned account.
To address this issue, we'd like to refund approximately 22 ATOM. Could you please provide the receiving address for the refund?

**Comment by An0rak21** [comment]
Hello @Ryz0nd and Keplr team, thank you for your partially reassuring response.

With about 50 people from our community, we decided to create two Multisigs to test your tools, introduce some newcomers to the Cosmos ecosystem, and make a collective investment.

We have locked in the two Multisigs **42.01 $ATOM**.
Multisig addresses:

1. cosmos17pfkgamvsdz2qvemr8f9nhvn6aekgwz7r3kzfs 
2. cosmos1nl0t9c5756q0mqdfrds6mh7srl6hct5hy8784p

We hope to be able to recover our funds as soon as possible in order to distribute them to 7-signatory multisigs and continue our journey through the Cosmos.

You can return the funds to the project founders at the address:
cosmos1r8j04j5udpc3hnjc4z38x9w5flmt8ddzdql54j

If you wish to contact the founders:

    - @BullBiDoo on Twitter
    - bullbidoo@gmail.com
    - You can also visit us on Discord: https://discord.gg/njbJZTyWWd

**Comment by Ryz0nd** [comment]
Hello @An0rak21.

We have just processed a refund of 42.01 $ATOM to the provided address: [cosmos1r8j04j5udpc3hnjc4z38x9w5flmt8ddzdql54j](https://www.mintscan.io/cosmos/tx/7058ACEAE5AA567E60F3F644BF183F92229549C61068C8377EE3BB49B7109711?height=18861574).

If you have any further questions or concerns, feel free to reach out. We appreciate your understanding and cooperation.
