### ISSUE TITLE
blank dashboard on Brave browser

### ISSUE THREAD

**Issue by haikosan** [chainapsis/keplr-wallet#1036]
I recently added a new wallet to my existing one using the Keplr extension on the Brave browser. Unfortunately, I didn't save the recovery phrase. I used to log in to my accounts and switch between them just by entering the Brave Keplr extension and switching between accounts.

However, today I thought my account might have been compromised. I logged into the extension, but I couldn't access the Keplr dashboard. I couldn't access Leap wallet or Osmosis, anything. I tried deleting my browser's cookies and cache, but that didn't resolve the issue.

So, I decided to reinstall the extension. After importing the recovery words from my main wallet, I realized that the second wallet wasn't added. To make matters worse, I attempted a system recovery, and my laptop was restored to a previous state on January 17, 2024. Unfortunately, this didn't help, and now I can't even launch the Brave browser.

Is there a way to restore the second wallet from the main? I saw it can be done with the ldb file for metamask, but its not working with the ldb file from Keplr.

**Comment by claraexmachina** [comment]
If you haven't already saved your recovery phrase, unfortunately, we won't be able to assist you in restoring your account.

**Comment by HeesungB** [comment]
@haikosan 
In Metamask, one Recovery Phrase creates multiple accounts, 
but in Keplr, one Recovery Phrase is one account.
The second account seems to be hard to recover.

**Comment by HeesungB** [comment]
@HeesungB You're welcome, glad you found it.
