### ISSUE TITLE
[bug][text][strong important]

### ISSUE THREAD

**Issue by Kwaskoff** [chainapsis/keplr-wallet#1054]
It is very strong important to correct the incorrect text that misleads a huge number of newbies!
![image](https://github.com/chainapsis/keplr-wallet/assets/15308024/b8db12c5-0de3-42ab-88c0-019bfc78d34d)
No with Veto is NOT the strongest opposition vote. It's not opposition vote totally! 

No with Veto is our instrument for slashing of a proposal depositor. That's it. 
This is an anti-spam tool.
Maybe this is an instrument of fighting against too arrogant proposals (let’s say someone asks for funding, and if refused, asks for funding again).

But this is never the strongest opposition vote.

Please!

**Comment by claraexmachina** [comment]
Hi. thank you for bringing this to our attention. We will update the explanation to: 

"No with Veto" signals a proposal infringes on minority interests, is spam, or breaches governance procedures. A proposal fails if over ⅓ vote "No with Veto".
