### ISSUE TITLE
Recuperación de direcciones

### ISSUE THREAD

**Issue by 1408eduardo** [chainapsis/keplr-wallet#1056]
**Describe the bug**
Recuperar cuentas de el correo jeduardogruiz@gmail.com que son admin de dao, Juno, neutron y cosmostation
**To Reproduce**

**Expected behavior**

**Screenshots**

**Device details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Browser: [e.g. Chrome Version 79.0.3945.79 (Official Build)]
 - Keplr Version: [e.g. 0.9.8 - find it on Extension tap(browser at the top right, click More(3 dots) > More tools > Extensions]
 - Hardware Wallet: [e.g. Ledger Nano S Firmware version 1.6.0]

**Additional context**
Add any other context about the problem here...
```

```

**Comment by HeesungB** [comment]
@1408eduardo Hello. I don't think I understood it correctly
Could you please write a little more in English?
