### ISSUE TITLE
Keplr Wallet error when exist another wallet extension

### ISSUE THREAD

**Issue by phongdatgl** [chainapsis/keplr-wallet#1061]
I got an error when have an other wallet extension already installed with Keplr.

![keplr-error](https://github.com/chainapsis/keplr-wallet/assets/3400817/96b23d20-de26-48d1-901e-88f54888566e)

**Comment by HeesungB** [comment]
@phongdatgl Hello.
This error occurs when another wallet tries to override the Keplr wallet.

If this doesn't work, try disabling the other wallet and using Keplr.
