### ISSUE TITLE
Keplr can't add a chain when other wallet plugins exist

### ISSUE THREAD

**Issue by shiyicode** [chainapsis/keplr-wallet#1062]
**Describe the bug**
<img width="1374" alt="Xnip2024-02-24_02-19-37" src="https://github.com/chainapsis/keplr-wallet/assets/12529091/31f40995-9ddd-404e-a37b-776b545354ca">

**Device details (please complete the following information):**
 - OS: OS X
 - Browser: Chrome Version 121.0.6167.184 (arm64)]
 - Keplr Version: 0.12.70

**Comment by HeesungB** [comment]
@shiyicode Hello.
I think another wallet is blocking my Keplr wallet's permissions
Deactivate the other wallet and try
