### ISSUE TITLE
Biometric authentication on iOS is not working.

### ISSUE THREAD

**Issue by erandakarachchi** [chainapsis/keplr-wallet#1069]
**Describe the bug**
Biometric authentication on iOS is not working even though it is enabled from the settings.

**To Reproduce**
1. Make sure you have logged at least once to the Keplr app.
2. Under the settings section, make sure the "Use Biometric Authentication" is turned on.
3. Now close the app and it will log you out automatically.
4. Open the app again and click on "Use Biometric Authentication" label under the "Unlock" button.
5. Observe the label changes to a spinner but does nothing.

**Expected behavior**
App should prompt me to authenticate myself with face Id.

**Screenshots**
## Login Page
https://github.com/chainapsis/keplr-wallet/assets/60935597/7c305467-c584-4f81-b6e0-7ac61aeec367

## Settings Page
![IMG_0867](https://github.com/chainapsis/keplr-wallet/assets/60935597/669ed341-adb7-4f6f-941d-9118f7aed412)

**Device details (please complete the following information):**
 - OS: iOS 17.2.1 (iPhone 13 pro)
 - Browser: N/A
 - Keplr Version: 2.0.31 (Build number 121)
 - Hardware Wallet: N/A

**Additional context**
None

**Comment by HeesungB** [comment]
@erandakarachchi Hello.
Can you please check if it's the same if you turn off and on the `use biometric authentication` permission in the security tab of the settings page?

**Comment by erandakarachchi** [comment]
> @erandakarachchi Hello. Can you please check if it's the same if you turn off and on the `use biometric authentication` permission in the security tab of the settings page?

Yes it worked. Thanks.
