### ISSUE TITLE
Keplr can't get second derivative address from Ledger

### ISSUE THREAD

**Issue by reednaa** [chainapsis/keplr-wallet#1074]
**Describe the bug**
I can't get the second derivative address. It is stuck on "Please connect your Hardware wallet" and step 2: Open Cosmos app on your ledger device.

**To Reproduce**
1. Create New Wallet
2. Click "Connect Ledger"
3. Input Wallet name
4. Advanced
5. Input 188 / 1
6. Click "Next"
7. Connect Ledger
8. Open Cosmos app.
9. Click "Connect"
10. Click "Connect"
11. Go to 9.

**Expected behavior**
It created a wallet for me using the second derivative.

**Screenshots**

![IMG_5213 – mellem](https://github.com/chainapsis/keplr-wallet/assets/58189177/e1e15f51-27bc-43a9-aef6-b1721201ae70)
![IMG_5214 – mellem](https://github.com/chainapsis/keplr-wallet/assets/58189177/18e8be15-8b13-47de-a846-893b86e1e7cd)

**Device details (please complete the following information):**
 - OS: iOS 17.3.1
 - Keplr Version: App Version: 2.0.31, Build Number: 121, Code Version: None
 - Hardware Wallet: Ledger Nano X, Cosmos app v2.34.9

**Comment by HeesungB** [comment]
@reednaa Hello. 

Open the cosmos app on your Ledger device. Press the right button to access the Expert mode screen. Then, press both buttons simultaneously to enable `Expert mode`.

![DSCF3197 (1)](https://github.com/chainapsis/keplr-wallet/assets/32606183/453912a9-d66b-48c0-809a-91db1b317a6a)


In the `m / purpose' / coin_type' / account' / change / address_index` bip44 path, ledger is throwing an error if both the account value and address_index value are above 100.

**Comment by reednaa** [comment]
@HeesungB It is still not working.
![IMG_5215 – mellem](https://github.com/chainapsis/keplr-wallet/assets/58189177/d45b0d48-7ca4-4189-88f5-74f0c2596420)

This is also a strange "solution" considering that Ledger Live is able to derive the address:
<img width="503" alt="image" src="https://github.com/chainapsis/keplr-wallet/assets/58189177/21a24f84-2af5-4d21-a421-c7a6d61b4b9d">

**Comment by HeesungB** [comment]
Keplr takes inputs from three digits after

So you would enter 1,0,0

Note that there is a ... after 44

118 is omitted because it is the coin type of Cosmos

**Comment by reednaa** [comment]
Thanks it worked. I didn't notice the ...
