### ISSUE TITLE
Latest version of Keplr corrupted

### ISSUE THREAD

**Issue by sruPL** [chainapsis/keplr-wallet#1080]
**Describe the bug**
Extension won't enable anymore, browser says it's corrupted.

**To Reproduce**
1. Open browser
2. Browser throws error, that extension has been disabled, because it might be corrupted
3. Clicking on 'Repair' doesn't help, in the extension tab

**Expected behavior**

Extension worked for 2-3 years just fine, something broke only now.

**Screenshots**

![image](https://github.com/chainapsis/keplr-wallet/assets/28690262/ef8d0740-8ed2-4330-9347-577619545f65)

**Device details (please complete the following information):**
 - OS: Windows 11
 - Browser: Opera ver. 108
 - Keplr Version: latest 0.12.75
 - Hardware Wallet: -

**Additional context**
Using extension for Opera to install Chrome extensions.

**Comment by sruPL** [comment]
Reinstalling solved the issue, but I would still look into that.

**Comment by HeesungB** [comment]
@sruPL The Opera browser is not officially supported by us.
