### ISSUE TITLE
App is ignoring sent fees

### ISSUE THREAD

**Issue by StrathCole** [chainapsis/keplr-wallet#1094]
**Describe the bug**
When sending gas fees to the keplr mobile wallet, these are ignored and overridden by the app.
This leads to the fact that taxable transactions on terra classic cannot be executed when using wallet connect with keplr mobile.

**To Reproduce**
Go to wallet.terra-classic.io
Connect using keplr mobile
Go to my wallet
Click on the send button and fill out the form, check the data in the mobile app

**Expected behavior**
Gas fees sent by the dApp should be respected by the app.

![Screenshot_20240411-213559](https://github.com/chainapsis/keplr-wallet/assets/7449529/ffba1a9e-972d-467d-8a29-1374d3b4515c)
![Screenshot_20240411-213621](https://github.com/chainapsis/keplr-wallet/assets/7449529/83e0bad3-d497-4920-9eee-43f74493e3d7)

**Comment by HeesungB** [comment]
@StrathCole Keplr does not automatically assign a Tax value.
You need to add it as a `preferNoSetFee` option on `terra-classic` website.

I think you should contact `terra-classic` website developer.

**Comment by HeesungB** [comment]
@StrathCole There is no documentation on mobile, but it works the same as the extension.
