### ISSUE TITLE
Error: SIGN_MODE_DIRECT can't be signed on Ledger.

### ISSUE THREAD

**Issue by 99Kies** [chainapsis/keplr-wallet#1135]
![image](https://github.com/chainapsis/keplr-wallet/assets/45918704/5beb17c0-5a3b-45d4-867a-c77f52fc2945)

**Comment by HeesungB** [comment]
@99Kies `Ledger` only supports `sign mode amino`.
I understand that `sign mode direct` is not supported because it is hard to read.
