### ISSUE TITLE
GasPrice error

### ISSUE THREAD

**Issue by DimaGavrushko** [chainapsis/keplr-wallet#1174]
Our application uses Keplr, for evm transactions also.

After the latest release [v0.12.118](https://github.com/chainapsis/keplr-wallet/releases/tag/v0.12.118) for some reason you automatically pass invalid gasPrice to transaction body and that breaks it execution.
<img width="365" alt="image" src="https://github.com/user-attachments/assets/b3db14e4-3607-4ff0-9ffd-ebbdba3f9dfc">
As the result we got an error for every evm transaction.
<img width="332" alt="image" src="https://github.com/user-attachments/assets/b4a9dd03-52a8-4103-aef2-5b490d47f632">

Nothing changed on our side, we pass valid maxFeePerGas and maxPriorityFeePerGas.

Maybe something should be fixed on our side, but I didn't find any new documentaion about last release.
I will appreciate any help, thanks.

**Comment by delivan** [comment]
Hey @DimaGavrushko, can you give the link where you try to send tx?

**Comment by delivan** [comment]
@DimaGavrushko Yes I do

**Comment by DimaGavrushko** [comment]
@delivan 
https://test.xficonsole.com/

You should:
1. Login with keplr
2. Go to evm/wallet 
3. Send XFI

But I think you need some test coins. If yes, you can write to my work email dmitriy.gavrushko@dfmx.ae and provide 0x address. I will send you some coins for test

**Comment by delivan** [comment]
@DimaGavrushko Can you give some coins to `0x7F7Ec812297f74c80Fc8bCaf11ac881DC88eb216`? Thank you.

**Comment by DimaGavrushko** [comment]
> @DimaGavrushko Can you give some coins to `0x7F7Ec812297f74c80Fc8bCaf11ac881DC88eb216`? Thank you.

Done
https://test.xfiscan.com/tx/0xd7207fb80ec669890ee722fb063fb2319205db7db1f65d416c48f86fd8f31801

**Comment by delivan** [comment]
It's a bug on our side. It will be fixed if [this](https://github.com/chainapsis/keplr-wallet/pull/1175) is published. Thank you for reporting this.

**Comment by DimaGavrushko** [comment]
> It's a bug on our side. It will be fixed if [this](https://github.com/chainapsis/keplr-wallet/pull/1175) is published. Thank you for reporting this.

Thanks for the prompt solution
