### ISSUE TITLE
Claiming Atom always must be done twice

### ISSUE THREAD

**Issue by trancephorm** [chainapsis/keplr-wallet#1191]
It's always that it needs to claimed 2 times to be claimed fully. It happens for quite some time now, like a year and it's not getting fixed.

**Comment by Thunnini** [comment]
It is intended behavior. If you delegated to many validators, there is a risk that the tx gas limit may exceed the block gas limit when making claim rewards, so up to 8 messages are sent. If you delegated to more than 8 validators, you will need to send tx multiple times.

**Comment by trancephorm** [comment]
Thank you!
