### ISSUE TITLE
Problems displaying IBC transfers in Dora

### ISSUE THREAD

**Issue by 99Kies** [chainapsis/keplr-wallet#1212]
Hi team, I'm using keplr for IBC transfer, the display of keplr never indicates that the transfer was successful, but actually the transaction was successful and I received the corresponding token on osmosis.  Can you check the status of dora for us? Please let me know if you need any support.

![image](https://github.com/user-attachments/assets/e772d66d-4dd6-4158-b628-85884660b26d)

**Comment by case-hub** [comment]
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. 
Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@99Kies 
Support.
  {c}2024
