### ISSUE TITLE
⚠️ Wrong coinType when using Ledger with Keplr

### ISSUE THREAD

**Issue by arno01** [chainapsis/keplr-wallet#125]
It looks like Keplr-extension on Ledger [generates](https://github.com/chainapsis/keplr-extension/blob/8201fc3c832331f36909880af08d83bfafe1aa1f/packages/background/src/ledger/service.ts#L29-L32) all Cosmos-based addresses using only coinType: `118` very much likely breaking the compatibility with any other dedicated wallets such as Cosmostation, [Crypto.org Chain Desktop Wallet](https://github.com/crypto-com/chain-desktop-wallet/releases), .... (i.e. people using Keplr-extension with Ledger will be getting different addresses for non-ATOM tokens.)

Interestingly, some tokens seem to use either `118` (ATOM) or their own coinType, i.e. IRIS `566` https://github.com/chainapsis/keplr-extension/blob/2119bdb1802e6f2f0c3f19071c9818a84416b20d/packages/extension/src/config.ts#L739-L744

According to [SLIP-0044 : Registered coin types for BIP-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) each coin does seem to have own unique `coinType`.

To make this work as expected, Keplr would need to request different App on Ledger (with proper coinType) for different token, IIUC.

## Refs
- https://github.com/chainapsis/keplr-extension/issues/95#issuecomment-877674055

**Comment by arno01** [comment]
cc @Thunnini

**Comment by Thunnini** [comment]
@arno01 Apologies for the late response. Ledger enforces security sandboxes by limiting different apps to one specific coin types. Therefore, any app using the Cosmos app must use the 118 cointype. Ledger stores the pubkey when supporting/registering the various chains, therefore it’s not possible to use other coin types for only specific chains.

If this is an absolutely crucial feature, the best way to approach it would be to allow users which Ledger app they’d prefer to use when they first import their Ledger into Keplr. However, please note that this would require additional implementation and we can’t give exact ETA on when it would be available.

**Comment by arno01** [comment]
@Thunnini thank you for your reply!

I think this is a really important and crucial feature as more users to come into the community going to have more and more confusion / "lost"-funds/potentially trust. Proof to that would be this issue https://github.com/chainapsis/keplr-extension/issues/95 where the user already started to notice the difference in the addresses. (As well as I did, but as I'm technically skilled I've managed to figure this out.. but most of the users - won't.)

I understand that the additional implementation would require additional time, that's fine and understandable.

But before that, it'd be nice to **have some warning for the Ledger users** about that fact that Hierarchical Deterministic (HD) derivation path is fixed to `118` for all underlying assets in the Keplr which can produce different than expected addresses. And some message that editable `coinType` (based on the ledger app) is a Work-in-progress feature coming in the future, maybe even with the link to the relevant github issue for sake of clarity. 

As we are early and I am not aware of Ledger app supporting any other `coinType` than `394` [CRO](https://github.com/LedgerHQ/app-cryptocom) for Cosmos-based tokens, I think, adding **the first non-`118` **coinType** wallet** available on Ledger would be a good starting point for Keplr and a platform for adding more to come.

Keplr would also need to **tell the user** to open the relevant Ledger app, i.e. [Crypto.org ledger app](https://github.com/LedgerHQ/app-cryptocom) for the wallet with different **coinType** to sync with the Ledger.

BTW, I'm wondering if Ledger could allow changing **coinType** directly from the [Cosmos-app](https://github.com/LedgerHQ/app-cosmos), i.e. have some in-app option such as "Select chain" where the users could select the relevant to him chain for the underlying Keplr's wallet?
Then, the already created wallets by Keplr would need some **indicator for the user to see,** i.e. a red label called `Non-standard coin type` with a tool-tip hint to a link or directly with the text explaining the user what is it.
And maybe even **prevent Keplr from automatic creation** of wallets except for the **coinType** `118` (ATOM) so the user can see the list of other chains and an option "**Create wallet...**" against each chain in the list of the Keplr, and then **the user can have an option** to create the wallet with the correct **coinType** when supported and warned/informed about the default **coinType** `118` when is NOT supported.

**Comment by sinN89** [comment]
This has to be fixed. I faced the same issue and was asking myself, why it isn't the same wallet.
Hopefuly like arno01, I managed to understand whats going on.

But it's not a proper way to do things for the lambda user who will search for his crypto. We don't have to remember wallet / derivation path and so on. We have to connect our ledger and get instant access to our crypto from the official wallet / correct coin type. If not, funds can be lost.

Then, I cannot manage my stake from your wallet as it's not the same...

Thanks,

**Comment by DarkGhost7** [comment]
When can we add Terra's app addresses coinType: 330 to keplr? @RiccardoM

**Comment by RiccardoM** [comment]
> @RiccardoM Why is the kepr import ledger address stuck to 118? I understand the cosmos ledger app would need that but this is separate no? see https://docs.terra.money/SDKs/Terra-js/Keys.html#mnemonickey

I'm not part of the Keplr team. I'm just a user like you who would like to see the support for custom apps inside Keplr as well.

**Comment by dogemos** [comment]
Hi @arno01,

We are currently not planning on adding support for other Ledger apps. I've summarized some of the nuances and thoughts on this matter [on this blogpost](https://medium.com/chainapsis/keplr-explained-coin-type-118-9781d26b2c4e).

We're working with multiple stakeholders (including Ledger) for a more long-term and sustainable path to interchain address derivation and standardization. This will involve the finalization of sign mode textual, and hopefully a 'interchain'-focused Ledger app that supports the feature.
