### ISSUE TITLE
Add ability to use custom API endpoints for sending txs

### ISSUE THREAD

**Issue by joe-bowman** [chainapsis/keplr-wallet#159]
As a: keplr user
I want: to be able to submit transactions via custom API endpoints
so that: when nodes are offline, transactions can be routed via different nodes

Example:

This evening, I am unable to send a TX to microtick via Keplr - the query fails - but I have an RPC endpoint I could adequately use in it's place, but have no option to override. sad times.

**Comment by daniel-farina** [comment]
I have the same question, how can we verify the endpoints Kepler is using?  I'm getting a lot of 501 errors when using Kepler but not when using my app making the calls directly to the blockchain's api. 

Is there a way to debug the calls from Kepler?

**Comment by wimel** [comment]
With recent attacks like the Polygon attack I think **this functionality becomes more important**, will it be possible to implement it? For those of us who use our own nodes to help decentralise the network it would be interesting to be able to make use of it.

**Comment by Thunnini** [comment]
This feature will be added in next v0.10.12 version.
