### ISSUE TITLE
Legacy endpoint /txs with stargate v0.44 keplr transaction fails with basic send-token

### ISSUE THREAD

**Issue by cybermelons** [chainapsis/keplr-wallet#167]
For a chain built with cosmos sdk v0.44, I can't send tokens to another wallet. Keplr returns a 501 from attempting to make a request to `localhost:1317/txs`. Seems like transactions don't get broadcasted to the new endpoint.

```
background.bundle.js:32 

       POST http://localhost:1317/txs 501 (Not Implemented)
```

My keplr extension is a 0.9.4 (latest in chrome store at this writing).

I noticed some comments about relevant stargate changes mentioned [here](https://github.com/chainapsis/keplr-extension/commit/3ae6e876a36e2d918dfb553bee8443ac0e6bb144).

This [doc page](https://docs.keplr.app/api/suggest-chain.html) says

> For Cosmos SDK blockchains using cosmos-sdk v0.4+. (However, even if the stargate isn't set, Keplr will query "/cosmos/base/tendermint/v1beta1/node_info" to check if it succeeds. 

But the network tab in chrome dev tools never shows that `node_info` endpoint ever being queried.

How do we workaround this or should we just wait for a fix on keplr?

**Comment by cybermelons** [comment]
It worked. I had to add `features: ['no-legacy-stdTx'],` to my config.

**Comment by daniel-farina** [comment]
@Thunnini 
Follow up on this, a brand new starport app works fine with the app's wallet but Keplr is giving us 500 error. 

More details here: 

https://github.com/tendermint/vue/issues/128#issuecomment-962912965
Step by step to reproduce there and a live server to test it with.

Where was the `no-legacy-stdTx` setting added @cybermelons ?

**Comment by cybermelons** [comment]
Reference can be found in the keplr config, like the osmosis frontend here: https://github.com/osmosis-labs/osmosis-frontend/blob/master/src/config.ts#L916

in your own code, it'd look something like

```
window.keplr.experimentalSuggestChain({

                features: ['no-legacy-stdTx'],

                chainId: "osmosis-1",
                chainName: "osmosis",
                rpc: ...,
                rest: ...,
                // Staking coin information
                stakeCurrency: {
                    // Coin denomination to be displayed to the user.
                    coinDenom: "OSMO",
                    // Actual denom (i.e. uatom, uscrt) used by the blockchain.
                    coinMinimalDenom: "uosmo",
                    // # of decimal points to convert minimal denomination to user-facing denomination.
                    coinDecimals: 6,
...
```

**Comment by marinhoarthur** [comment]
Since I'm using solely the extension to try to send token and getting the 501 error, the adding of such a flag via JS seems out of place as in where would I configure this if it's just the extension that I'm using and not via my web application?

Just to clarify If I try to sign the transaction using my web application using Keplr, I get success. If I try to send using the extension only, I get 501.

cc @Thunnini 

<img width="341" alt="image" src="https://user-images.githubusercontent.com/3693700/142434996-7237008e-e4c6-4d28-9d1c-89eefff2ab3c.png">

**Comment by marinhoarthur** [comment]
update:

I tried **first removing** the chain from Keplr and adding it again with the `no-legacy-stdTx` flag on. It worked.

Even then, should we look out for Keplr not auto adding that flag? Maybe to avoid future incompatibilities like this?

**Comment by daniel-farina** [comment]
This is great news. 
Thank you @marinhoarthur

**Comment by Rodri-R** [comment]
Adding the no-legacy-stdTx flag worked for us too!!

Thank you

![no-legacy-stdTx-works](https://user-images.githubusercontent.com/46242399/142703775-faf4fdde-d093-4c68-99bf-2eca833a6ca3.png)

**Comment by terryyyyyy** [comment]
> > Where was the `no-legacy-stdTx` setting added @cybermelons ?
> 
> You'd want to specify it as a feature when your app suggests its chain to keplr
> 
> The osmosis frontend does it here: https://github.com/osmosis-labs/osmosis-frontend/blob/master/src/config.ts#L916
> 
> in your own code, it'd look something like
> 
> ```
> window.keplr.experimentalSuggestChain({
> 
>                 features: ['no-legacy-stdTx'],
> 
>                 chainId: "osmosis-1",
>                 chainName: "osmosis",
>                 rpc: ...,
>                 rest: ...,
>                 // Staking coin information
>                 stakeCurrency: {
>                     // Coin denomination to be displayed to the user.
>                     coinDenom: "OSMO",
>                     // Actual denom (i.e. uatom, uscrt) used by the blockchain.
>                     coinMinimalDenom: "uosmo",
>                     // # of decimal points to convert minimal denomination to user-facing denomination.
>                     coinDecimals: 6,
> ...
> ```

I just use cosmos-hub4 chain, need i SuggestChain in the frontend code?
