### ISSUE TITLE
Re-initialized Keplr does not recognize activated tokens on secret network

### ISSUE THREAD

**Issue by gboor** [chainapsis/keplr-wallet#214]
A few weeks ago a friend and I did an experiment that involved me setting up an SCRT wallet with Keplr and my Ledger Nano S and my friend sending me some SCRT so I could activate the sXMR token using the Monero Secret Bridge. This all went fine; sXMR showed up as a token with a 0 balance and I left it at that.

Yesterday, I decided to actually use the Monero Secret Bridge and get some sXMR to experiment with. When opening Keplr, I could not remember what password I had set up. But since it was tied to my ledger, that didn't seem like a problem. I uninstalled Keplr, reinstalled it and set it up with my ledger again. My SCRT balance showed up and I was able to transfer it - no problems so far.

However, the sXMR token did not show up at all and when trying to use the Monero Secret Bridge, it comes back saying I need to activate the sXMR token again and pay for that. I checked my wallet on secretnodes.com and there are only 3 items in the history; receive some SCRT from my friend, "interact" with sXMR_token_v3 contract (which is the sXMR token activation) and send out some SCRT. It's pretty clear to me that the history shows this token was activated on this wallet.

I tried adding the sXMR token by address as well, but Keplr again pops up saying I need to pay for the transaction.

I don't really care about the 5c I have to pay to activate it again, but this does seem like a pretty serious bug and it also makes me wonder if my sXMR balance would even be available if I need to reset the wallet again.

Is there any way to manually add the sXMR token again without reactivating it? Can Keplr not see what tokens should be available from the wallet history?

Curious to hear about other people's experiences.

**Comment by dogemos** [comment]
This is because we treat viewing keys similar in the same way as private keys. The keys are only stored locally after being encrypted–but separate from the mnemonic. Importing the account with the mnemonic only allows you to get the private key, but viewing keys will have to be imported separately.

Please export, and store your viewing keys from the extension or reset the viewing keys on-chain.
