### ISSUE TITLE
Signature verification failed: when account number is 0

### ISSUE THREAD

**Issue by angelorc** [chainapsis/keplr-wallet#217]
## Summary of Bug
When an account number `0` tries to sign any transaction always gets the following error: 

```
Broadcasting transaction failed with code 4 (codespace: sdk). Log: signature verification failed; please verify account number (0) and chain-id (localnet): unauthorized.
```

## Versions
- CosmJS - `v0.26.5`
- Cosmos-SDK - `v0.42.10`

## Step to Reproduce
1. Start a new chain `v0.42.10`
2. Add 2 accounts
3. Import the first (account 0) and the second (account 1) to Keplr
4. Connect keplr with your application `window.getOfflineSigner(chainId)`
5. Send tokens from the account 0
   ```
	{
		"typeUrl": "/cosmos.bank.v1beta1.MsgSend",
		"value": {
			"fromAddress": "bitsong1vgpsha4f8grmsqr6krfdxwpcf3x20h0q3ztaj2",
			"toAddress": "bitsong1vgpsha4f8grmsqr6krfdxwpcf3x20h0q3ztaj2",
			"amount": [
				{
					"amount": "1000000",
					"denom": "ubtsg"
				}
			]
		}
	}
	```
	- The transaction receive an error
	  ```
	  Broadcasting transaction failed with code 4 (codespace: sdk). Log: signature verification failed; please verify account number (0) and chain-id (localnet): unauthorized.
	  ```
6. Send tokens from the account 1
   ```
	{
		"typeUrl": "/cosmos.bank.v1beta1.MsgSend",
		"value": {
			"fromAddress": "bitsong1zm6wlhr622yr9d7hh4t70acdfg6c32kcv34duw",
			"toAddress": "bitsong1zm6wlhr622yr9d7hh4t70acdfg6c32kcv34duw",
			"amount": [
				{
					"amount": "1000000",
					"denom": "ubtsg"
				}
			]
		}
	}
	```
	- The transaction will pass `Successful Send`

## Side note

If instead we try to perform the same operation via command line (`bitsongd tx send.....`) no errors are found.
The bug isn't related to cosmjs https://github.com/cosmos/cosmjs/issues/961

**Comment by Thunnini** [comment]
At a glance, it should be skipped when the account number is 0, but it seems to be a problem because it is encoded as 0. Let me explore some more about protobufjs.
https://github.com/chainapsis/keplr-extension/blob/master/packages/cosmos/src/stargate/proto/generated/codecimpl.js#L2982

**Comment by Thunnini** [comment]
Looking at cosmjs, it seems that cosmjs uses https://github.com/stephenh/ts-proto. The protobufjs currently used by keplr includes the default value on encoding, and there seems to be no way to prevent it.
First of all, since I have never used ts-proto, this issue is unlikely to be resolved in the next version.

Either use ts-proto or manually modify the output from the compiled protobufjs.
