### ISSUE TITLE
Phrase not shared via KEPLR Extension

### ISSUE THREAD

**Issue by brewsterdrinkwater** [chainapsis/keplr-wallet#218]
I tried signing up for a Keplr wallet via the chrome extension on mac desktop, while attempting an Akash Deploy. When I connected KEPLR wallet to Google Account, I was NOT given the 12 word phrase. There was no where for me to locate the 12 word phrase within the extension, and my password access for KEPLR was as simple as putting in Google credentials.

**Comment by dogemos** [comment]
Hi @brewsterdrinkwater, for Keplr accounts created with Google logins–you will get access to the same address if you login with the same Google account.

If you'd prefer to backup something more concrete (always a good practice), you can back up the hex formatted private key by going to the 'accounts' menu -> '...' button -> show private key and keeping your private key stored safely.
