### ISSUE TITLE
501 error for AMINO transactions

### ISSUE THREAD

**Issue by shinigami-kun** [chainapsis/keplr-wallet#222]
Hey,

I'm facing with 501 error on my dapp hours ago after the Osmosis update,

using keplr.sendTx(chainId, signedTx, BroadcastMode.Async)

I got a 501 error after the user signs the transaction.

any hint to fix it?

**Comment by Thunnini** [comment]
After cosmos-sdk@0.44.x, the  POST /txs endpoint completely deleted. As you can see here https://github.com/chainapsis/keplr-extension/blob/v0.9.9/packages/types/src/wallet/keplr.ts#L76, `sendTx` sends the tx to the POST /cosmos/tx/v1beta1/txs endpoint if the tx is `Uint8Array`. I don't know what you use to send tx. However, you need to encode the tx by protobuf.

**Comment by shinigami-kun** [comment]
Yeap, i have fixed it by adding proto messages.

**Comment by terryyyyyy** [comment]
> Yeap, i have fixed it by adding proto messages.

Hi, I faced the same issue. How to create proto messages from stdTx?

**Comment by terryyyyyy** [comment]
@Thunnini Hi, I faced the same error 501 on cosmoshub-4. How can sendTx by Keplr? I have make the signed tx(stdTx).

**Comment by TunaMoney** [comment]
> @Thunnini Hi, I faced the same error 501 on cosmoshub-4. How can sendTx by Keplr? I have make the signed tx(stdTx).

hi terry. have you figured out a solution sending protobuf tx? been trying for awhile with no luck.
