### ISSUE TITLE
Help With Keplr Wallet Transferring

### ISSUE THREAD

**Issue by AlpinePress** [chainapsis/keplr-wallet#227]
Greetings,
I did something stupid today trying to claim the Codex airdrop. There is a scam Comdex Telegram group and I went to their link to try and claim. 
I'm now trying to move my assets from my original Keplr wallet to a new account that I added to my existing email. I have a new seed phrase, and it looks like new addresses were added to each chain.
Is there an easy way to transfer over all of my assets (staked and unstaked) from my original account to my new added account?
Thanks,

Bret Smith

**Comment by delivan** [comment]
Hi @AlpinePress 

Unfortunately, there is no way to transfer over all of assets, and you should unstake your staked assets if you want to transfer.

Thanks.
