### ISSUE TITLE
All Terra UST tranfers failing

### ISSUE THREAD

**Issue by AdamJLemmon** [chainapsis/keplr-wallet#234]
Hey team, can not find a means to contact your support so logging here...

All of your Terra txs sending UST are failing.
The below error is blowing across the top of the extension no matter the gas set.
Kindly advise of a fix or where to chat further.

Thanks!

```
Fail to send token: insufficient fees; got: "3000uluna", required: "38000uaud,38000ucad,28000uchf,196000ucny,180000udkk,25000ueur,22000ugbp,234000uhkd,436000000uidr,2176000uinr,3274000ujpy,33954000ukrw,2266uluna,85714200umnt,250000unok,1520000uphp,20988usdr,250000usek,40000usgd,924000uthb,34865uusd" = "38000uaud,38000ucad,28000uchf,196000ucny,180000udkk,25000ueur,22000ugbp,234000uhkd,436000000uidr,2176000uinr,3274000ujpy,33954000ukrw,2266uluna,85714200umnt,250000unok,1520000uphp,20988usdr,250000usek,40000usgd,924000uthb,30000uusd"(gas) +"4865uusd"(stability): insufficient fee
```

**Comment by dogemos** [comment]
Terra isn't a natively supported chain, and is permissionlessly added through the 'suggest chain' feature. They have a separate fee logic which is different from the standard Cosmos SDK fee logic, which means UST transfers are not currently supported on Keplr. Please use the [Terra Station](https://chrome.google.com/webstore/detail/terra-station/aiifbnbfobpmeekipheeijimdpnlpgpp?hl=en) wallet for full Terra support.
