### ISSUE TITLE
[bug]: Cannot import a keplr wallet in terra station

### ISSUE THREAD

**Issue by Milerius** [chainapsis/keplr-wallet#235]
**Describe the bug**

According to: https://keplr.crunch.help/general-questions/ust-transfer-in-keplr UST transfer doesn't work for Terra and we need to use Terra station. However, I cannot import the keplr wallet into terra station using the private key. It seems that the private key of the keplr wallet is not compatible with any terra wallet. How to get the terra private key directly?

I created my keplr wallet with my google account so I don't have a mnemonic.

**Expected behavior**

The possibility of having access to the private key of each of the coin or a means of transferring the UST.

**Comment by dogemos** [comment]
Hi @Milerius,

We can't export private keys into a Terra Station formatted private key, as they use a custom armored private key which is non-standard. Perhaps you can reach out to the Terra Station team to allow importing of general hex formatted private keys.

Terra isn't a supported chain on Keplr and one that is added to Keplr via the permissionless suggest chain feature. Please use LUNA to transfer the assets to a Terra Station account.
