### ISSUE TITLE
Chrome Displays: "Your Keplr extension is outdated (v0.1.5). Please update your extension to v0.8.0+. Update instructions"

### ISSUE THREAD

**Issue by Ross2266** [chainapsis/keplr-wallet#237]
Whey I attempt to access Keplr dashboard at [https://wallet.keplr.app/#/dashboard], wallet no longer connects and a ribbon at the top of the page displays "Your Keplr extension is outdated (v0.1.5). Please update your extension to v0.8.0+. Update instructions" (see image). Kepler browser wallet is logged in and appears to be functioning normally, but just wont connect with web page. I can not currently see any of my staking balances or other account info.

OS: Windows 11 Pro
Chrome: Version 96.0.4664.110 (Official Build) (64-bit)
Kepler Extension Version: 0.9.10

![image](https://user-images.githubusercontent.com/96900210/147803814-bba06669-17ac-426b-903d-0264998472ee.png)

**Comment by Thunnini** [comment]
Go to chrome://extensions/ and disable all extension wallets other than keplr and try again.

**Comment by Thunnini** [comment]
If the above solution solves the problem, please let me know which extension is the problem.

**Comment by Ross2266** [comment]
THANK YOU, PROBLEM HAS BEEN SOLVED. 

I noticed the issue after adding Fetch.ai Network Wallet 0.1.5 and Terra Station Wallet 1.21.2, so I suspect it was caused by the interaction with one of those.

Thanks
