### ISSUE TITLE
Bug: Import terra station wallet in Keplr

### ISSUE THREAD

**Issue by deFaup** [chainapsis/keplr-wallet#242]
Numbers of people have realized that after using their TerraStation mnemonic phrase in Keplr (to restore an existing Terra account) they get a different Terra address. Both wallet have the same mnemonic but the Terra address is different.

**To Reproduce**
1. Install Keplr chrome browser extension
2. Open Keplr extension and Click on 'Import existing account'
3. Enter your mnemonic phrase
4. fill out the rest
5. Click next
Add the colombus-5 network to the wallet (you can go to https://app.osmosis.zone/ to add it) and then witness in the wallet that your Terra address is different than in TerraStation

Trying with the Terra private key didn't work either. In Terra station the Export Private Key feature returns a base64 encoded json, this encoded value cannot be imported in Keplr. And if I take from the decoded json the encrypted key it doesn't work either.
In both case it says Too short mnemonic. Even if this private key feature was fixed I believe we would end up with the issue described above.

https://www.reddit.com/r/cosmosnetwork/comments/qgzfl4/access_main_terra_wallet_on_keplr/
https://www.reddit.com/r/terraluna/comments/rcaijk/adding_terra_station_seed_to_keplr_wallet/
https://www.reddit.com/r/OsmosisLab/comments/r3nigo/is_there_a_way_to_import_an_existing_terra/

**Comment by downing034** [comment]
Stumbled on this issue when going to log my own related to Terra. The issue could be related to cointype or config setup with:
> Add the colombus-5 network to the wallet (you can go to https://app.osmosis.zone/ to add it) and then witness in the wallet that your Terra address is different than in TerraStation

This is using the `experimentalSuggestChain` which requires custom config for the chain you're connecting to. It looks like Terra is setup for keplr mobile [here](https://github.com/chainapsis/keplr-wallet/blob/master/packages/mobile/src/config.ts#L995), but does not exist in the setup for the extension [here](https://github.com/chainapsis/keplr-wallet/blob/master/packages/extension/src/config.ts).

If the config ends up being the issue, maybe getting Terra added to the extension config.ts will resolve the issue.

**Comment by deFaup** [comment]
Impressive, thank you for pointing this out. Can we update the config of the chain we're adding to the extension?

**Comment by downing034** [comment]
[Here](https://github.com/osmosis-labs/osmosis-frontend/blob/993d33e44f6c99c59df303b27f03e8c0a23423c2/src/config.ts#L701) is the current Terra config setup in osmosis and it actually looks similar to the one in the [keplr extension](https://github.com/chainapsis/keplr-wallet/blob/master/packages/mobile/src/config.ts) itself, so adding the config as a default option to the extension config may not end up fixing your issue.

That being said, it would be nice to have in the extension if it's already supported in mobile

**Comment by jacobcoro** [comment]
I made a [PR](https://github.com/chainapsis/keplr-wallet/pull/252), but they DO say that they won't accept coin support PR's. Although they are already supporting it on mobile so maybe it will work.
