### ISSUE TITLE
Firefox Support for Keplr Browser Wallet

### ISSUE THREAD

**Issue by vanthome** [chainapsis/keplr-wallet#245]
I think Firefox is a must, although it's maybe not used as much, FireFox is certainly more in line with the idea of decentralization than other browsers. Polkadot gets this right with their Polkadot.JS wallet.

**Comment by Retrodynen** [comment]
any news on this?

**Comment by Olyno** [comment]
Unfortunately, I understand that it's not the developers' priority to deal with this @Retrodynen

**Comment by Retrodynen** [comment]
that's a huge shame if that's the case

**Comment by ofersht** [comment]
no firefox wallet? :(

**Comment by kkuubb** [comment]
This would really be awesome, using chrome based browsers just for keplr is a little exhausting

**Comment by RomanHiden** [comment]
I support this as well

**Comment by ofersht** [comment]
> This would really be awesome, using chrome based browsers just for keplr is a little exhausting

What are you using to access your cosmos wallet?

**Comment by ornato-t** [comment]
> I was able to build the extension locally and it ran fine on Firefox, everything worked as expected. Not sure what is the team decision behind not releasing this on Firefox :l

Did you use a hardware wallet or just the mnemonic?
I packed the release code and ported it to Firefox but when I tried to import my Ledger it failed to detect it.

**Comment by orpheuslummis** [comment]
A first step is to specify exactly what is needed to reach full Firefox support.

**Comment by orpheuslummis** [comment]
I commit to fund 100 USD-equivalent for this issue if a bounty on Gitcoin is created for it. I expect this would fund only 2-10% of the needed work though.

**Comment by Olyno** [comment]
For unknown reasons, the developers did not communicate on this issue concerning the development of the extension on Firefox. I just saw that they released Keplr on Firefox in beta (https://www.keplr.app/download).

Feel free to go test this beta version and give feedback!

![image](https://user-images.githubusercontent.com/25107942/204424264-6c76d1de-4816-47fe-bc20-ce39a69c63ef.png)

**Comment by matslats** [comment]
I've installed on firefox but now I can't see how to open the app.
Should there be a launcher button next to the other firefox extension buttons?|
is there a way to launch extensions without a button?
