### ISSUE TITLE
🐛 Error while trying to deposit Regen tokens to Osmosis. 

### ISSUE THREAD

**Issue by DenisRebenok** [chainapsis/keplr-wallet#261]
I encountered an error trying to deposit regen tokens to Osmosis. 
Got an error every time: _0.814464REGEN is smaller than 6REGEN: insufficient funds (at msg 0)_. But I have a lot of regen tokens in a wallet and tried to deposit just 6 regens. 
<img width="1522" alt="1" src="https://user-images.githubusercontent.com/8539872/151112194-422372c0-3992-4335-bc97-c6efb4d90e0d.png">
<img width="1672" alt="2" src="https://user-images.githubusercontent.com/8539872/151112202-b1938f5e-717c-4963-8084-bd08f947d193.png">

Did anyone get a similar problem? How it can be fixed?

**Comment by DenisRebenok** [comment]
Also, I capture a short video (18 sec) that describes the full process of deposit
I reinstalled Keplr extension, tried to deposit using other fresh Chrome profiles, and tried to do it in another browser - Brave. Got the same errors. So I have not any other thoughts about what else to try 🤷🏻‍♂️

https://user-images.githubusercontent.com/8539872/151243172-1e6b0a46-1cda-41e4-91b4-f1f1d40e5fb8.mov

**Comment by dogemos** [comment]
Is this a vesting account by any chance?
