### ISSUE TITLE
Validators Status

### ISSUE THREAD

**Issue by chmichael** [chainapsis/keplr-wallet#262]
Hello,
  Please add the "Status" in the staking validator list (eg. Jailed or Ok) in order to avoid staking/redelegating into "Jailed" validators!
  
  Thank you

**Comment by ChrisGxT** [comment]
This. I just got locked out of rewards for 21 days, because of a jailed validator using the same name as a legit validator in the drop-down menu of the redelegate action.

**Comment by chmichael** [comment]
Made a new issue for this:
https://github.com/chainapsis/keplr-wallet/issues/266

It appears Keprl is showing inactived and jailed validators!

**Comment by chmichael** [comment]
Solved by https://github.com/chainapsis/keplr-wallet/issues/266
