### ISSUE TITLE
URGENT: Keprl shows inactive validators to delegate!

### ISSUE THREAD

**Issue by chmichael** [chainapsis/keplr-wallet#266]
Hello,
  When you try to delegate/redelegate Keprl will show inactive or double/triple same validators!
  Attached screenshot!

  
![KKK1](https://user-images.githubusercontent.com/13120950/151674329-2c3a6186-2bd2-4e7d-ae37-c1c22b85a278.jpg)

**Comment by chmichael** [comment]
More people start to have problems!
https://www.reddit.com/r/cosmosnetwork/comments/sfsu4n/psa_pay_attention_to_the_validators_you_delegate/

**Comment by dogemos** [comment]
added labels to the redelegation selection.
