### ISSUE TITLE
Keplr wallet doesn't work with last ledger firmware 2.02

### ISSUE THREAD

**Issue by Milerius** [chainapsis/keplr-wallet#271]
(issue self explanatory)

**Comment by Thunnini** [comment]
Which OS and web browser are you using?

**Comment by Milerius** [comment]
Solved after restarting the ledger, was probably a miss cache configuration

**Comment by chmichael** [comment]
@Milerius Next time close the Cosmos App from the ledger and reopen it! 
(Seems chrome looses the Ledger detection for some reason)
