### ISSUE TITLE
Support for ERC20 Tokens on Gravity Bridge

### ISSUE THREAD

**Issue by TokenV1** [chainapsis/keplr-wallet#281]
Gravity Bridge provides a transfer of nearly every ERC20 token to the G-Bridge Chain.
With ChainInfo there is an option to configure up-font what ERC tokens have been whitelisted

`
Currency(
coinDenom: "wETH",
coinMinimalDenom:
"gravity0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
coinDecimals: 18),
Currency(
coinDenom: "DAI",
coinMinimalDenom:
"gravity0x6B175474E89094C44Da98b954EedeAC495271d0F",
`
Denom is prefix of "gravity0" + ERC20 Contract Address

It would be helpful if we could add dynamically a currency for tokens, based on ERC20 contract address.

I'm not familiar with chrome extensions, the question here is: Could the web site from where I connecting the Keplr Wallet provide an interface or a service as a callback which can be consumed by the Keplr Wallet? 
As far as I understood, IBCCurrency read the data from an endpoint, could be implemented a similar interface where the data provider would be the web site itself to inject the supported currencies ?

You can try it out here: https://bridge.blockscape.network. We have pre-registered DAI, WETH, USDT, USDC on Keplr.
More details you get here: https://blockscape-network.medium.com/how-to-use-the-gravity-bridge-portal-ad24887b230e

The picture below shows how it look like with pre-registered ERC 20 Tokens like WETH and DAI.

<img width="289" alt="Screenshot 2022-02-11 at 10 19 18" src="https://user-images.githubusercontent.com/82452629/153565868-cd9bec94-9bfe-4177-a7c2-d955c38fc4d1.png">

**Comment by dogemos** [comment]
Do you think you can make a PR similar to [this](https://github.com/chainapsis/keplr-wallet/pull/247/files)?

**Comment by dee-effes** [comment]
Hey there, I'm part of @TokenV1 's team.  We could create a config like this. The problems with that are that there are quite a few erc20 tokens, and that we will need to add more tokens as native cosmos tokens are deployed on ethereum. Are there any limitations on how many currencies a configuration like the one you linked can specify? And is it possible for keplr to fetch more currencies via the gravity rpc?
