### ISSUE TITLE
26.6 OSMO disappeared from my Keplr wallet right after an ATOM transfer to my Binance wallet failed

### ISSUE THREAD

**Issue by DeepRabbit81** [chainapsis/keplr-wallet#294]
26.6 OSMO disappeared from my Keplr wallet right after an ATOM transfer to my Binance wallet failed

Last night I attemped to transfer $181 worth of ATOM from my Keplr wallet to my ATOM Binance wallet. As I sent the funds, my $232 OSMO balance instantly went to zero, as well as my ATOM balance.

The funds have never reached Binance, nor have they returned to my Keplr wallet.

I'm new here and I don't know if this forum exists to deal with this type of thing, so if I'm in wrong place, please accept my apologies. I just didn't know where or who to turn to.

In case anyone can help me out, my Keplr wallet is cosmos1mt2s54uaqq0mjfl4nff9tas5p50uuzyjc6mxry (maybe there's a way to find out what happened in the blockchain?)

Thanks,
Luis

**Comment by chmichael** [comment]
Use reddit for such type of problems: https://www.reddit.com/r/cosmosnetwork/
Also take a look at https://www.mintscan.io/cosmos (enter you cosmos address) to find out what happen.
