### ISSUE TITLE
Cannot advance through "Verify Mnemonic" due to repeat word in seed phrase

### ISSUE THREAD

**Issue by ebfull** [chainapsis/keplr-wallet#296]
During the "Create a new wallet" section of wallet setup, when proceeding to create a new mnemonic seed phrase, my wallet generated a phrase that happened to contain the same word twice (in this case, it was "census"). After writing down the seed phrase I was prompted to fill in random spots of the phrase to see if I truly wrote it down, to guard against users lazily avoiding writing it down.

However, I was prevented from advancing through the "Verify Mnemonic" window because once I selected the word "census" to fill in the first spot, later on in the phrase where "census" appears a second time I could not select it again because it was greyed out. If I attempt to press "census" a second time to fill it out, it ungreys "census" but then removes "census" from the earlier position in the seed phrase I already filled in. And thus I cannot proceed and must start all over.

![screenshot](https://i.imgur.com/jktwS3q.jpg)

I'm experiencing this on the Android version of the Keplr wallet downloaded from the Play store, 1.0.18 build 22.

**Comment by X-Tyler** [comment]
+1

**Comment by X-Tyler** [comment]
Proceeding with an "invalid" seed should be allowed through acceptance of warning notification.
