### ISSUE TITLE
Remove support of the launchpad

### ISSUE THREAD

**Issue by Thunnini** [chainapsis/keplr-wallet#297]
The launchpad version of cosmos-sdk seems to be deprecated. Currently, the launchpad version chain is only straightedge and is rarely used.
It is difficult to manage stargate and launchpad at the same time.
Also, legacy query seems to disappear completely in the next version of cosmos-sdk. Currently, a lot of legacy queries are also used to support lauchpad, but the use of legacy queries should be eliminated by terminating support for launchpad.
Also, if this PR https://github.com/cosmos/cosmos-sdk/pull/11234 is passed, the performance of the grpc gateway will increase significantly, so let's use the grpc gateway.

**Comment by nooomski** [comment]
Hey, looks like this is becoming an [issue](https://github.com/cosmos/cosmos-sdk/issues/11374) for front-ends interfacing with a v0.46 SDK chain. Was wondering if there was a timeline on a fix by any chance @Thunnini ?
