### ISSUE TITLE
Allow zero gas when signing arbitrary messages

### ISSUE THREAD

**Issue by mikedotexe** [chainapsis/keplr-wallet#299]
**Is your feature request related to a problem? Please describe.**
When trying to sign an offline message, use ADR36, Keplr is unable to attach zero gas.

**Describe the solution you'd like**
I've been looking into the offline signing and the signed typed data and have found ADR36, which seems to be in Draft but coming along.

If you look at the [Decisions section of ADR36](https://github.com/cosmos/cosmos-sdk/blob/master/docs/architecture/adr-036-arbitrary-signature.md#decision), we'll see:

**fee gas must be equal to 0**

**Describe alternatives you've considered**
I've heard that I can set the zero gas fee using something like this:

```js
window.keplr.defaultOptions = {
  sign: {
    preferNoSetFee: true,
  },
};
```

**Additional context**
There's a closed PR that might be worth a glance: https://github.com/chainapsis/keplr-wallet/pull/205

**Comment by Thunnini** [comment]
Check this https://github.com/chainapsis/keplr-wallet/issues/207
