### ISSUE TITLE
Support Ledger S USB connection on Keplr mobile (Android)

### ISSUE THREAD

**Issue by NicolasMassart** [chainapsis/keplr-wallet#305]
**Is your feature request related to a problem? Please describe.**

Kepler android doesn't recognise ledger s Hardware wallet but only works with ledger X.

**Describe the solution you'd like**

As a user I would love to be able to connect my ledger s on my android phone using usb and be able to have it work with Keplr android app

**Describe alternatives you've considered**

Using desktop for the moment. I also have a ledger X, but my coins are on the ledger s and I think as the ledger s is far less expensive, it would help new comers to secure their funds to have it work with mobile keplr

**Additional context**

**Comment by dogemos** [comment]
Hi @NicolasMassart,

Unfortunately, due to the amount of additional engineering effort needed, Ledger Nano S support for mobile app is not on our near-term roadmap.

Will put this as something to do once we have additional engineering resources available.

Best,
