### ISSUE TITLE
iOS Keplr wallet app goes blank white after launch with faceID check

### ISSUE THREAD

**Issue by zhanghe2030** [chainapsis/keplr-wallet#315]
**Describe the bug**
iOS Keplr wallet app goes blank white after launch with faceID check

**To Reproduce**
1. Start the Keplr Wallet app
2. After check the face ID
3. See a blank white screen.

**Expected behavior**
Solve it and save the data on the mobile app

**Screenshots**

**Device details (please complete the following information):**
 - OS: [iOS 15.3.1, iPhone 12]
 - Keplr Version: 1.0.17

**Additional context**

**Comment by zhanghe2030** [comment]
I do know delete and restore the wallet may solve the issue. But i made a very stupid mistake and thought it's register with only username and password. 
Right now i am really freak out and worried if we could solve this bug. Please help to fix it...... :((((

**Comment by Thunnini** [comment]
@zhanghe2030 On the Keplr Lock screen, do not unlock screen right away, but wait 10 seconds, repeat this about 2~3 times, and Keplr would be auto updated. After the app gets updated, the issue should be solved. If so, save your mnemonic in a safe place and close this issue for us!
