### ISSUE TITLE
A problem where the response is cut off when the size of the response is large on IOS

### ISSUE THREAD

**Issue by Thunnini** [chainapsis/keplr-wallet#318]
In iPhone, when the size of the response is large, the response value is status 200 (OK), but the response data is returned truncated. As a result, the return value is treated as a string instead of an object, resulting in a type error.

This problem only occurs on some iPhones. So it is difficult to test in real environment.
But we should handle this case because this problem makes the app unusable.

It's not an error, but the response data itself is sent strangely, so it's difficult to handle it perfectly in the frontend...
If the content type is application/json, data is string, and it starts with `{`, it is assumed that this is an error caused by this problem and handled as an error. It is an incomplete solution, but there is no problem in the cases of the query currently used in keplr. Let's use this method until we fundamentally fix the bug that the response data is handled incorrectly in the native stage, but status 200 (OK) is returned.

#315
#278

**Comment by zhanghe2030** [comment]
Thanks for fixing this bug
