### ISSUE TITLE
Missing code on https://docs.keplr.app/api/

### ISSUE THREAD

**Issue by wgwz** [chainapsis/keplr-wallet#328]
**Describe the bug**

There seems to be some missing code/API docs on https://docs.keplr.app/api/. I.e. in the [Get Address / Public Key](https://docs.keplr.app/api/#get-address-public-key) section.

![image](https://user-images.githubusercontent.com/10120306/158679820-0f408c5a-9737-457d-982e-f04bf01172ed.png)

**To Reproduce**
1. Go to https://docs.keplr.app/api/#get-address-public-key
2. See missing code

**Expected behavior**
Docs more in sync with: https://github.com/chainapsis/keplr-wallet/tree/master/docs/api

**Comment by Thunnini** [comment]
Probably solved
