### ISSUE TITLE
Keplr still pending even if the transaction is validated.

### ISSUE THREAD

**Issue by terryyyyyy** [chainapsis/keplr-wallet#331]
In my front-end code, I use SigningStargateClient from @cosmjs/stargate and keplr as offlineSigner, the code below. But when user approve the transaction in keplr window, the button is loading all the time even if the transaction is validate on blockchain, and the window of keplr still pending, i need to close the window by click the close button.

`const keplr = await getKeplr()
await keplr.enable(chainId)
const offlineSigner = window.getOfflineSigner(chainId);

const fee = {
  amount: [{
    denom: 'uatom',
    amount: '7000'
  }],
  gas: "260000"
}
console.log('start');

const client = await SigningStargateClient.connectWithSigner(cosmosAuthApiUrl, offlineSigner)
const res = await client.signAndBroadcast(store.state.cosmos.cosmosAccount, msgs, fee, memo)
if (res.code === 0) {
  console.log('Transaction hash:', res.transactionHash);
  resolve(res.transactionHash)
}`

I use chrome in mac. The rpc node is: https://cosmoshub.validator.network/
![7361647767871_ pic](https://user-images.githubusercontent.com/15071907/159156224-f6443e07-6d63-48a7-b9af-04adbf46e2cc.jpg)

**Comment by dogemos** [comment]
Please make sure that websocket is enabled on the RPC endpoint that you're connected to.

Keplr uses the websocket connection to verify that the transaction has completed, which means that an websocket error/websocket being disabled can lead to txs appearing it's in a pending state even when it has confirmed.

**Comment by helloheesu** [comment]
I'm going through the same problem. It happens on all the sites I use including Osmosis, whereas my friends use them all good. Even with same wallet account, it works well on other PCs.
So I think RPC endpoint's not the problem in my case. I tried removing the chain info from Keplr and added suggested info again, but still the same problem happened. What should I try more?
