### ISSUE TITLE
Feature request: Custom RPC/API Node(s)

### ISSUE THREAD

**Issue by ctrl-Felix** [chainapsis/keplr-wallet#341]
### Problem 
The Keplr wallet is currently using hard coded nodes to broadcast transactions. While there weren't any major issues with those nodes they are a single point of failure and in case of a problem the addon isn't usable anymore. And I don't need to mention that Keplr is the only wallet which is integrated with all major applications in the Cosmos ecosystem. I don't know the keplr infrastructure but a good DDOS might be already enough to interrupt the usability of the wallet. Furthermore we've seen with MetaMask that a node hoster be asked by the legal authorities to geoblock certain areas/countries.

### Solution
A possible solution would be to allow the user to enter a custom rpc/api endpoint in the settings to broadcast his transactions and query data. Another solution would be to provide a list of rpc nodes from which the use can choose his own node.
Both solutions are compatible with each other and would ensure decentralisation as well as uninterruptible functionality.

### Sources
MetaMask temporarily not working in Venezuela due to Infura geoblocking => https://www.coindesk.com/business/2022/03/04/crypto-industrys-sanctions-woes-on-full-display-in-metamasks-venezuela-hiccup/

**Comment by ctrl-Felix** [comment]
The osmosis frontend is down due to keplr peer issues!

**Comment by ctrl-Felix** [comment]
**Update**
After the osmosis upgrade now the chain is back but Keplr isn't as the Keplr nodes aren't updated...

A custom rpc feature could speed up this

**Comment by wimel** [comment]
Related with #159 this feature is so important. Please add this.

**Comment by Thunnini** [comment]
This feature will be added in next v0.10.12 version.
