### ISSUE TITLE
Transactions on Sentinel chain doesn't work

### ISSUE THREAD

**Issue by Freak12Techno** [chainapsis/keplr-wallet#344]
**Describe the bug**

When submitting any transaction on Sentinel network, the request fails with error 501. Apparently `POST https://lcd-sentinel.keplr.app` fails with HTTP 501, causing this.
It all started with Sentinel upgrade 2 days ago so it should be the cause.
A lot of people on Sentinel group are reporting this, so it shouldn't be only me.

**To Reproduce**
Submit any transaction on Sentinel chain.

**Expected behavior**
Transaction is broadcasted

**Screenshots**
![photo_2022-04-02 14 41 14](https://user-images.githubusercontent.com/83376337/161381476-62a927e0-cec7-4e94-bf34-30820fd89855.jpeg)

**Device details (please complete the following information):**
 - OS: Mac OS X
 - Browser: Brave (though it doesn't seem to be a browser issue, everything worked before)
 - Keplr Version: 0.9.18
 - Hardware Wallet: Ledger Nano X

**Additional context**

**Comment by Thunnini** [comment]
Which website doesn't work?

**Comment by Freak12Techno** [comment]
@Thunnini wallet.keplr.app and the ability to do any txs from here, it does seem like it won't work anywhere as it's LCD server endpoint that fails

**Comment by Thunnini** [comment]
It works now?

**Comment by Freak12Techno** [comment]
Works for me and at least one other validator confirmed it works for him. What was the issue?

**Comment by Thunnini** [comment]
The extension can reflect the chain update automatically, but the web does not.

**Comment by Freak12Techno** [comment]
Thanks for a quick fix!
