### ISSUE TITLE
Log: unable to resolve type URL /cosmwasm.wasm.v1.MsgExecuteContract: tx parse error

### ISSUE THREAD

**Issue by coolpapa715** [chainapsis/keplr-wallet#346]
This is my transaction data via keplr
{
  "txBody": {
    "messages": [
      {
        "sender": "terra1ptywzlfy47c338j62ax7acs8rjvqems0ptv0gv",
        "contract": "terra1v93ll6kqp33unukuwls3pslquehnazudu653au",
        "msg": "eyJzd2FwIjp7Im1heF9zcHJlYWQiOiIwLjA1Iiwib2ZmZXJfYXNzZXQiOnsiaW5mbyI6eyJuYXRpdmVfdG9rZW4iOnsiZGVub20iOiJ1bHVuYSJ9fSwiYW1vdW50IjoiMTAwMDAifSwiYmVsaWVmX3ByaWNlIjoiMS4wMDIwMDQwMDgwMTYwMzIifX0="
      },
      {
        "sender": "terra1ptywzlfy47c338j62ax7acs8rjvqems0ptv0gv",
        "contract": "terra1kc87mu460fwkqte29rquh4hc20m54fxwtsx7gp",
        "msg": "eyJzZW5kIjp7Im1zZyI6ImV5SmtaWEJ2YzJsMFgyTnZiR3hoZEdWeVlXd2lPbnQ5ZlE9PSIsImFtb3VudCI6Ijk0ODEiLCJjb250cmFjdCI6InRlcnJhMXB0anAydmZqcndoMGowZmFqOXI2a2F0bTY0MGtnanhud3dxOWtuIn19"
      },
      {
        "sender": "terra1ptywzlfy47c338j62ax7acs8rjvqems0ptv0gv",
        "contract": "terra1tmnqgvg567ypvsvk6rwsga3srp7e3lg6u0elp8",
        "msg": "eyJsb2NrX2NvbGxhdGVyYWwiOnsiY29sbGF0ZXJhbHMiOltbInRlcnJhMWtjODdtdTQ2MGZ3a3F0ZTI5cnF1aDRoYzIwbTU0Znh3dHN4N2dwIiwiOTQ4MSJdXX19"
      },
      {
        "sender": "terra1ptywzlfy47c338j62ax7acs8rjvqems0ptv0gv",
        "contract": "terra1sepfj7s0aeg5967uxnfk4thzlerrsktkpelm5s",
        "msg": "eyJib3Jyb3dfc3RhYmxlIjp7ImJvcnJvd19hbW91bnQiOiI2NTMwMDAifX0="
      },
      {
        "sender": "terra1ptywzlfy47c338j62ax7acs8rjvqems0ptv0gv",
        "contract": "terra1sepfj7s0aeg5967uxnfk4thzlerrsktkpelm5s",
        "msg": "eyJib3Jyb3dfc3RhYmxlIjp7ImJvcnJvd19hbW91bnQiOiIxMDAwIiwidG8iOiJ0ZXJyYTFsa2tyNmQzcGRlNmQ3MDBhcHFzbGFta2twdmZ0cGxnNm1qcnp4OSJ9fQ=="
      },
      {
        "sender": "terra1ptywzlfy47c338j62ax7acs8rjvqems0ptv0gv",
        "contract": "terra1sgu6yca6yjk0a34l86u6ju4apjcd6refwuhgzv",
        "msg": "eyJzd2FwIjp7Im1heF9zcHJlYWQiOiIwLjA1Iiwib2ZmZXJfYXNzZXQiOnsiaW5mbyI6eyJuYXRpdmVfdG9rZW4iOnsiZGVub20iOiJ1dXNkIn19LCJhbW91bnQiOiI2NTMwMDAifSwiYmVsaWVmX3ByaWNlIjoiMTA5LjY1NTc1MTQ2OTM1MzQ5In19"
      },
      {
        "sender": "terra1ptywzlfy47c338j62ax7acs8rjvqems0ptv0gv",
        "contract": "terra1tus5ec9qsdht8dapq9ldfnsf8eehnfmwvsut83",
        "msg": "eyJzd2FwIjp7Im1heF9zcHJlYWQiOiIwLjA1Iiwib2ZmZXJfYXNzZXQiOnsiaW5mbyI6eyJuYXRpdmVfdG9rZW4iOnsiZGVub20iOiJ1bHVuYSJ9fSwiYW1vdW50IjoiNTgwNiJ9LCJiZWxpZWZfcHJpY2UiOiIwLjAwMTA1NTM0OTUwMDQ1Mzk2NyJ9fQ=="
      }
    ],
    "memo": "Borrow"
  },
  "authInfo": {
    "signerInfos": [
      {
        "publicKey": {
          "type_url": "/cosmos.crypto.secp256k1.PubKey",
          "value": "CiECs8rBpq/BtzCLHi6H/Su4fCPb0HKNSRmRD7LiNLwDGiU="
        },
        "modeInfo": {
          "single": {
            "mode": "SIGN_MODE_DIRECT"
          }
        }
      }
    ],
    "fee": {
      "amount": [
        {
          "denom": "uluna",
          "amount": "3000"
        }
      ],
      "gasLimit": "200000"
    }
  },
  "chainId": "columbus-5",
  "accountNumber": "3773033"
}

but I get this error : Log: unable to resolve type URL /cosmwasm.wasm.v1.MsgExecuteContract: tx parse error

How can I fix this error?

**Comment by Thunnini** [comment]
Please visit terrais on this issue.

**Comment by shakibaei65** [comment]
Hello, Hello, thank you for your repeated answers. I apologize for the delay in responding. Yes, I accept the law of this wallet, I hope it helps me to unlock my frozen currencies .. I really have a question if you can help me solve my problem .. I remember you well and I wish you happiness .. ..
my friend. The fact is, I can not unlock my cryptocurrencies so that their value can be seen in my wallet. Teach me to solve my problems
