### ISSUE TITLE
v3 manifest

### ISSUE THREAD

**Issue by Laboratory** [chainapsis/keplr-wallet#354]
Hello, 

Is there a plan to support manifest v3?

As of [January 17, 2022] Chrome Web Store has stopped accepting new Manifest V2 extensions. We strongly recommend that new extensions target [Manifest V3]. 

it turns out I can't publish the extension for testing without changing the code.

**Comment by Thunnini** [comment]
I am aware of this issue. But, due to lack of time, I can't solve this right now.
We have time to solve this because the existing extension can be updated until this year.
We plan to deep-dive in this issue and solve it at Q2-Q3 2022.
