### ISSUE TITLE
How does keplr broadcast transactions?

### ISSUE THREAD

**Issue by victor-wei126** [chainapsis/keplr-wallet#356]
For Ethereum, metamask is used as a centralized 3rd party. But how does keplr do it? Does it use a similar service? Or do you maintain your own set of nodes that you broadcast transactions to via http or some other transport?

**Comment by xwy88** [comment]
交易出现的问题，是什么原因导致的。
https://user-images.githubusercontent.com/34532109/163726738-fa109e41-1b87-41b2-a788-d8eb4966b113.mp4
![b3ff4373a98d54c40342810684e25f5](https://user-images.githubusercontent.com/34532109/163726747-54a87f90-4c15-47f5-9be5-3528a14578f9.jpg)

**Comment by dogemos** [comment]
Hi @victor-wei126

We operate most of our natively-integrated chain's infrastructure in-house, and Keplr transactions are currently broadcasted via our endpoints.
