### ISSUE TITLE
交易出错

### ISSUE THREAD

**Issue by xwy88** [chainapsis/keplr-wallet#360]
**Describe the bug**

https://user-images.githubusercontent.com/34532109/163726821-49decef7-b3ed-4a70-be53-2b145198266d.mp4

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Browser: [e.g. Chrome Version 79.0.3945.79 (Official Build)]
 - Keplr Version: [e.g. 0.9.8 - fi
![b3ff4373a98d54c40342810684e25f5](https://user-images.githubusercontent.com/34532109/163726823-2514aca5-9276-40ec-9c50-c3f126007ff7.jpg)
nd it on Extension tap(browser at the top right, click More(3 dots) > More tools > Extensions]
 - Hardware Wallet: [e.g. Ledger Nano S Firmware version 1.6.0]

**Additional context**

**Comment by Thunnini** [comment]
This issue is due to lack of gas. When you click 'set gas' at the bottom, double the gas and try sending it again.
And please use English, since I do not understand Chinese.
