### ISSUE TITLE
`KeplrError` type 추가하기

### ISSUE THREAD

**Issue by Thunnini** [chainapsis/keplr-wallet#367]
#314 

현재 오류를 처리할 때 따로 오류 타입을 만들지 않고 기본 Error만 사용해서 하고 있다.
하지만 #314 PR의 경우와 같이 가끔씩 특정 오류에 대해서는 다른 처리가 필요한 경우가 있다.
현재는 error.message를 직접 확인하는 방식으로 하고 있지만 이 방식은 관리하기 어렵다.

### TODO
- `KeplrError` 타입을 추가한다.
- `KeplrError` 타입은 code: number와 module: string을 필드로 가진다.
- background router와 message requester에서 `KeplrError` 오류의 경우 잘 처리해주도록 만든다.

**Comment by junhoyeo** [comment]
Reviews for #380 from @Thunnini ❤️ 

1. Do not sort imports for now
2. Add field `module`(for context) in `KeplrError`
3. `code` starts from 100 for each `module`
4. When comparing conditions, compare with `instanceOf`(further check needed), `module` and `code`. Do not compare with raw strings(such as `message`)
5. We may need to set explicit prototype when extending the default `Error`. Use `Object.setPrototypeOf(this, KeplrError.prototype)` (https://github.com/chainapsis/keplr-wallet/blob/master/packages/hooks/src/tx/errors.ts)
7. Place `KeplrError` in `@keplr-wallet/router`
  a. We have to add handlers; Errors are stringified when passed to `popup` <-> `background` <-> `content script`
  b. Register one generic message handler in https://github.com/chainapsis/keplr-wallet/blob/master/packages/background/src/chains/init.ts
  c. Currently we're just passing `{ error: 'message' }`: https://github.com/chainapsis/keplr-wallet/blob/master/packages/router-extension/src/router/extension.ts -> Change this to `KeplrError` fields
10. https://github.com/chainapsis/keplr-wallet/blob/master/packages/router-extension/src/requester/extension.ts
