### ISSUE TITLE
Ledger: Fail to send token: Data is invalid : Unrecognized error code

### ISSUE THREAD

**Issue by chmichael** [chainapsis/keplr-wallet#368]
**Describe the bug**

After updating the cosmos app on the ledger i can't send through IBC.
I throws: Fail to send token: Data is invalid : Unrecognized error code

**To Reproduce**
1. Update your ledger device with the latest cosmos app
2. From keprl go to osmosis chain
3. Select an IBC token (eg. Juno) and sent it to another Osmosis address
4. You'll get Fail to send token: Data is invalid : Unrecognized error code

Before the update of the cosmos app on ledger it worked.
Anyhow only the IBC transfer doesn't work the the updated cosmos app on ledger.

**Expected behavior**
To send the token to the other address

So something has changed either from the cosmos ledger app or the keprl.

Thank you

**Comment by sbacelic** [comment]
I get the same error, ledger, sending IBC tokens. Is there anything else we can provide in order to debug further?

**Comment by Thunnini** [comment]
What type of ledger (S, S plus, X) are you using? Which firmware version of ledger and cosmos app are you using? I can't reproduce this issue.

**Comment by sbacelic** [comment]
S plus, latest FW and cosmos app v2.34.3

**Comment by sbacelic** [comment]
When I use IBC transfer option at the bottom of the main screen then it works, when I select the particular token in the token list and try to send from there then I get the error. So I would say the problem is not the ledger.

**Comment by Thunnini** [comment]
It seems to be a problem with the latest version of CosmosApp in ledger, not with Keplr.
I'll take a look more.

**Comment by intercos** [comment]
![sif Err](https://user-images.githubusercontent.com/94884108/169691320-bb7f8451-ce36-4616-9b55-9371ba54d933.jpg)

Error when sending ATOM to another account address in Sifchain using Ledger.
"Fail to send token: Data is invalid : Unrecognized error code"

Keplr v0.10.4
Ledger nano X (Cosmos App v2.34.3 / v2.34.4)

Same issue with Cosmos App v2.34.3 / v2.34.4.

======================
On April 20st,
It was possible to send ATOMs to another account address in Sifchain
(using Cosmos App v2.34.3)

**Comment by chmichael** [comment]
Keprl: 0.10.4 Ledger app: 2.34.4 
Still the same issue!

I'm NOT talking about IBC Transfer!

Eg you have 1 juno asset in osmosis chain.
Click on the 1 Juno and sent it to another osmosis wallet.

This all started from upgrading the "Cosmos" Ledger app to the latest version before it was working fine!

Thank you

**Comment by intercos** [comment]
IBC Token(Juno): osmosis -> osmosis
It is not an IBC transfer.
It is a normal transport.
IBC transmission is when transmitted to another chain.

**Comment by dayakarreddyn** [comment]
> Keprl: 0.10.4 Ledger app: 2.34.4 (Nano X) Still the same issue!
> 
> I'm NOT talking about IBC Transfer!
> 
> Eg you have 1 juno asset in osmosis chain. Click on the 1 Juno and sent it to another osmosis wallet.
> 
> This all started from upgrading the "Cosmos" Ledger app to the latest version before it was working fine! @Thunnini if you think that it's still a ledger issue i should open a ticket there! (i did open check below)
> 
> Thank you

I Can confirm this is happening on omniflix marketplace as well. This is happening with IBC assets & MsgSend on same chain. Cross-chain transactions from osmosis to omniflix using MsgTransfer are all working fine.

**Comment by intercos** [comment]
>
Correction)
Before April 20th: Use Cosmos App v2.1.8
April 23th: Cosmos App v2.34.3 Update

The issue that is not transmitted to the IBC token in the same chain seems to be after the COSMOS app v2.34.3 update.

**Comment by intercos** [comment]
Test)
Keplr v0.10.5
Ledger Nano S: Firmware v2.1.0,  Cosmos App v2.18.0

IBC Token (ATOM)
Sifchain -> Sifchain
Send possible

I tested it today with my friend's Ledger Nano S.
If Ledger uses Cosmos App v2.18.0, IBC Token can be sent.

Conclusion)
The issue of IBC token send impossible
It's definitely something to do with the Cosmos app update.

**Comment by chmichael** [comment]
@Thunnini Ledger cosmos application 2.34.6 released today with the fix! So I'm closing the issue.
