### ISSUE TITLE
Please let PR 372 go in

### ISSUE THREAD

**Issue by derfredy** [chainapsis/keplr-wallet#377]
Dear @dogemos @sunnya97 @Thunnini and rest of the team.

This is a single digit change in chainId of a Network, and it is causing many user issues.
Please, let it go.

https://github.com/chainapsis/keplr-wallet/pull/372

**Comment by Thunnini** [comment]
It will be released soon, but currently there aren’t any issues even without this PR. Even if there is an issue it would be a separate issue, not something that #372 would solve

**Comment by sunnya97** [comment]
@derfredy keplr should automatically detect the change in chain-id and prompt the user to confirm updating it

**Comment by derfredy** [comment]
Thanks Thunnini and Sunny.
f
