### ISSUE TITLE
Manifest.json version upgrade

### ISSUE THREAD

**Issue by emrahm** [chainapsis/keplr-wallet#382]
Menifest V2 cannot be used at chrome at the beginning of 2023. So that i am trying to update it but i could not success to make it.
Backgroud page doesnt work or it does not go to correct browser implementation. I think it uses firefox at chrome.

When you want to update keplr wallet at chrome developer zone, you may probably take error like below.
Please upgrade manifest version.

"You can no longer publish new Manifest V2 extensions. Try converting your extension to Manifest V3."

https://developer.chrome.com/docs/extensions/mv3/intro/

**Comment by Thunnini** [comment]
Check this #354

**Comment by Thunnini** [comment]
I don't think it's something that we must do right now. But it will be done in a few months. Then I will make a separate issue at that time.

**Comment by emrahm** [comment]
Thanks for reply @Thunnini Keplr has cross browser feature but when we want to deploy it to Mozilla it has obstacle. max size should be 4MB. Our popup.bundle.js is approximately 5.6 MB. How can we deal with this issue.
