### ISSUE TITLE
Error sending IBC assets between addresses on the same chain after ledger upgrade

### ISSUE THREAD

**Issue by RoboMcGobo** [chainapsis/keplr-wallet#393]
After the latest ledger live update to v2.41.3 (which includes an update to the cosmos app, v2.34.4), users who upgrade to this version can no longer send IBC assets between addresses on the same chain. Example below:

Two separate users running the above ledger versions attempted to send IBC-denominated ATOM from one Osmosis address to another Osmosis address. They received the following error code and the transaction failed:

![image](https://user-images.githubusercontent.com/95544279/169592478-15599794-5cbf-4a36-b795-fd1eb62576ce.png)

Note that the above error code occurred both on the Keplr UI and attempting this same transaction via CLI

I was able to process this send with no issues from one wallet to another, but the wallets I used were not tied to a ledger. Based on that I think it's pretty likely that ledger is the cause of the issue here. IIRC I believe Keplr was just updated to v 0.10.4 so it's possible that might have something to do with this as well?

The user that helped me troubleshoot this is running the following: 

Brave Browser (version 1.38.119)
Kelpr (version 0.10.4)
For testing purposes they also tried this on Chrome (version 101.0.4951.67 (Official Build) (64-bit)) and got the same error.

I wasn't sure whether to open this issue here or on the Osmosis repo. If I'm in the wrong place please let me know and I'll port this over to the Osmosis repo.

**Comment by Thunnini** [comment]
Duplicated #368
