### ISSUE TITLE
Staking reward claim button does not update after claiming

### ISSUE THREAD

**Issue by goktug7913** [chainapsis/keplr-wallet#404]
**Description**
When claiming staking rewards, the button doesn't update to deactivated state with no rewards until a page refresh.

**To Reproduce**
1. Claim staking reward
2. Complete the transaction
3. The "Claim Reward" can be clicked again.

**Expected behavior**
After the transaction completes, the button should be disabled and available reward should be 0.

**Device details (please complete the following information):**
 - OS: Windows
 - Browser: Chrome Version 100.0.4896.75 (Official Build) (64-bit)
 - Keplr Version: 0.10.4
 - Hardware Wallet: None

**Additional context**
I've encountered this on OSMO, but probably it is reproduceable on other chains.

**Comment by Thunnini** [comment]
This problem may occur depending on the network conditions with the node. If it's a network problem, the frontend cannot solve it.
Another case is that you delegated to 9 or more validators. When sending claim rewards tx, only 8 claim rewards are given due to the max gas limit. So you may have to do multiple claim rewards.

**Comment by goktug7913** [comment]
> This problem may occur depending on the network conditions with the node. If it's a network problem, the frontend cannot solve it. Another case is that you delegated to 9 or more validators. When sending claim rewards tx, only 8 claim rewards are given due to the max gas limit. So you may have to do multiple claim rewards.

I've been encountering this since when I first started using Keplr, only delegating to single validator, so It might be a problem with OSMO node?
