### ISSUE TITLE
Ledger transactions fail if there is a less than or greater than symbol in the transaction.

### ISSUE THREAD

**Issue by ezekiiel** [chainapsis/keplr-wallet#417]
Steps to reproduce:

1. Attempt to send funds to an account and put a `<` or `>` symbol in the memo field while using a ledger.

This occurs if a less than or greater than symbol is anywhere in the transaction.

**Comment by JakeHartnell** [comment]
Have a feeling there might be other symbols too. When submitting a proposal for the Terra Dev Fund, it fails with:
```
Error: Broadcasting transaction failed with code 4 (codespace: sdk). Log: signature verification failed; please verify account number (#####), sequence (###) and chain-id (juno-1): unauthorized
```

My account number, sequence, and chain ID are right.

GET THIS, if I submit the TX again, copy the JSON from the Keplr approval window, and then sign with the CLI... *it works.*

**Comment by Thunnini** [comment]
#454 This PR will solve this issue.
