### ISSUE TITLE
Fail to send token: signature verification failed on genesis_29-2 and wrong public key imported from CLI

### ISSUE THREAD

**Issue by alpha-omega-labs** [chainapsis/keplr-wallet#419]
Hello,
Cosmos delegators recently received L1 coin in genesis_29-2 network. In tests about few weeks ago all tests were fine and after receiving coins, cosmos users were able to transact with Keplr.
Now users who received actual airdrop see their coins in Keplr after adding the genesis_29-2 network, however sending tx failed:
please verify account number (22470), sequence (0) and chain-id (genesis_29-2): unauthorized

Also importing private key from node CLI leads to wrong "other" public key (not same as in CLI).

Thank you

**Comment by alpha-omega-labs** [comment]
How to reproduce:

Create new keplr account/address 
Send L1 coins to this address - goes well
Send L1 coins from this address fail with:
"Fail to send token: signature verification failed; please verify account number (428101), sequence (0) and chain-id (genesis_29-2): unauthorized"

Unsigned transaction formed in Keplr looks like:

"chain_id": "genesis_29-2",
  "account_number": "0",
  "sequence": "0",
  
  Seems like problem is with path derivation: in account_number and/or sequence

**Comment by Thunnini** [comment]
I'm not sure what chain you're talking about, but looking at the chain id, it looks like it's probably an evmos fork. Currently, evmos-related codes are managed by the evmos team, and only chain created by the evmos team are officially supported (with beta). We do not solve any other problems that occur on the other chains.

**Comment by alpha-omega-labs** [comment]
Noted, thank you!
