### ISSUE TITLE
Dear Keplr, please be aware: Echelon chain is scam

### ISSUE THREAD

**Issue by alpha-omega-labs** [chainapsis/keplr-wallet#420]
Please, be aware, Echelon chain is a scam, According to blockchain analysis organization launched echelon 100% control consensus by controlling >67% of coins, pretending its decentralized. Echelon is spam, scam, pump and dump.

**Comment by Thunnini** [comment]
Don't worry, opening PR doesn't mean that it will be added as a native integrated chains.
The chains that are natively supported will be considered carefully within the Keplr team.

**Comment by alpha-omega-labs** [comment]
Great! Just gave heads up on findings! 
I think can be closed now :)
P.S. Can you please check issue 419

**Comment by echelonfoundation** [comment]
> 

We would love to get in contact with you guys to get our chain natively added, This person is a troll and a spammer, he has been opening issues all over lately attempting to FUD our project. The coins in circulation are all owned by the community, you can validate everything on all explorers. Join our Discord too https://discord.gg/echelon so you can meet the community yourself.

**Comment by echelonfoundation** [comment]
This person has no proof and it is a baseless accusation that is easily proven wrong by viewing our explorers and talking to the community and validators of the network.

**Comment by echelonfoundation** [comment]
This @alpha-omega-labs that is trolling our project seems to have a rival Cosmos SDK project also. Very unprofessional and unwelcoming. We have established markets on seven DEXs and three CEXs at this point, 45 out of 100 validators are online, we have a stablecoin on chain also "bUSDC" which is 1 to 1 to Binance Pegged US Dollar Coin. The circulating supply and everything to do with inflation and validators can be viewed at https://ping.pub/echelon

**Comment by alpha-omega-labs** [comment]
https://github.com/ethereum-lists/chains/issues/1216

**Comment by echelonfoundation** [comment]
We have reported you @alpha-omega-labs to Github, as you can see @Thunnini, he also has attacked us on the ethereum-lists Github. All facts have been given proof, we do not own >67% like what he claims, we have 3.8% that is going out in incentives to our community. Our network is 10x bigger than his scam Cosmos clone and we feature a custom bridge across seven of the most popular L1 EVMs.
