### ISSUE TITLE
Account number must be 1 or higher to send transactions.  Account number 0 is unable to send transactions as identified in this issue.

### ISSUE THREAD

**Issue by schnetzlerjoe** [chainapsis/keplr-wallet#422]
Account number must be 1 or higher to send transactions. 
Account number 0 is unable to send transactions as identified in [this issue](https://github.com/chainapsis/keplr-wallet/issues/217).

This was happening here https://github.com/chainapsis/keplr-wallet/issues/217. Is happening again. To replicate, try importing an account and then changing the password (underlyingly changing the sequence and the signature).

**Comment by alpha-omega-labs** [comment]
Confirming, same issue in several places, for example:
This might be related to sequence number,
Currently have issue with creation of Osmosis pool:

1. Blank new account receive asset X and Osmo in Osmosis mainnet
2. Pool creation leads to the following error:
You have too many concurrent txs going on! Try resending after your prior tx lands on chain. (We couldn't send the tx with sequence number 0)

Osmosis withdraw/deposit of asset is working. 

Also noticed that in account that is "old" sequence in tx is "-1", when it should be "8", its "7", and with same error.
