### ISSUE TITLE
Keplr Browser Extension goes blank after opening a few times

### ISSUE THREAD

**Issue by bigshooTer39** [chainapsis/keplr-wallet#431]
**Describe the bug**
The extension works fine for a little while.  If I open it a few times and/or change networks.  Then it will just turn white on me.  I have close the browser completely and reboot to be able to open Keplr extension.  it is incredibly annoying since the iOS app only supports a handful of chains.  The web wallet supports a few more but you can't add networks to it, so I have to rely on the extension or Cosmostation.  All other extensions work fine.  No other issues.

**To Reproduce**
Not sure

**Expected behavior**
Click on Keplr extension and be able to see wallet.

**Screenshots**
![Keplr Issue](https://user-images.githubusercontent.com/107437307/173440157-054329d4-789e-44b0-a529-ab7345f494b5.jpg)

**Device details (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave Browser V1.39.122 Chromium 102.0.5005.115
 - Keplr Version: Unable to because the extension opens just white.  Assume its the latest though.
 - Hardware Wallet: Ledger Nano X

**Additional context**

**Comment by Billy7745** [comment]
Hello team. Yesterday i transfer wFTM to my Keplr wallet with Kujira bridge and everything went fine. Now every time i try to enter Kujira with my Kepler wallet  the screen go blank but if i disconnect the wallet and i refresh Kujira site, i´m able to view Kujira. I tried with Chrome and Brave.
Can you help please?

**Comment by bigshooTer39** [comment]
I've come to find that this issue seems to occur when switching to a non-native chain such as MEME token or Assmantle.

**Comment by Thunnini** [comment]
Keplr supports some of the basic modules of cosmos-sdk. However, if an error occurs in the combination of keplr and non-native chain, it is a compatibility issue with that chain, not a problem in keplr. If the chains added from outside is not compatible with keplr, it is definitely the issue to that chain. Please contact to chain team.
