### ISSUE TITLE
Possibility to add cw20 tokens on testnets

### ISSUE THREAD

**Issue by kerber0x** [chainapsis/keplr-wallet#436]
**Is your feature request related to a problem? Please describe.**
I see it's possible to add token contracts to the wallet via the hamburger menu on main nets, yet the option disappear when you switch to a testnet, namely juno's uni-3.

**Describe the solution you'd like**
I don't see why the option to add tokens would not be available for testnets, it should be there.

**Describe alternatives you've considered**

**Additional context**

This is how the menu looks on juno mainnet 
![Screenshot from 2022-06-22 13-20-01](https://user-images.githubusercontent.com/94062656/175028031-165522e7-607f-4845-8204-24a16ca50c08.png)

This is how it looks on juno testnet 
![Screenshot from 2022-06-22 13-21-07](https://user-images.githubusercontent.com/94062656/175028104-0fa364a2-88ad-4365-b3ff-9e31391627b9.png)

**Comment by kerber0x** [comment]
So it has nothing to do with Keplr? Moreover, as I understand it, does it mean then that I could add the testnet from different websites and get different results?

**Comment by Thunnini** [comment]
Yes
