### ISSUE TITLE
Kujira site going blank

### ISSUE THREAD

**Issue by Billy7745** [chainapsis/keplr-wallet#449]
Hello team. Yesterday i transfer wFTM to my Keplr wallet with Kujira bridge and everything went fine. Now every time i try to enter Kujira with my Kepler wallet the screen go blank but if i disconnect the wallet and i refresh Kujira site, i´m able to view Kujira. 
I tried with Chrome and Brave and both sites are up to date.
Can you help please?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device details (please complete the following information):**
 - OS: [e.g. OS X, Windows]
 - Browser: [e.g. Chrome Version 79.0.3945.79 (Official Build)]
 - Keplr Version: [e.g. 0.9.8 - find it on Extension tap(browser at the top right, click More(3 dots) > More tools > Extensions]
 - Hardware Wallet: [e.g. Ledger Nano S Firmware version 1.6.0]

**Additional context**

**Comment by Thunnini** [comment]
Keplr supports some of the basic modules of cosmos-sdk. However, if an error occurs in the combination of keplr and non-native chain, it is a compatibility issue with that chain, not a problem in keplr. If the chains added from outside is not compatible with keplr, it is definitely the issue to that chain. Please contact to chain team.
