### ISSUE TITLE
keplr.experimentalSuggestChain({…}) missing gas setting

### ISSUE THREAD

**Issue by zccst** [chainapsis/keplr-wallet#452]
**Is your feature request related to a problem? Please describe.**

Currently using Keplr extension, the default gas value is 80000 during transfer, which is defined by Keplr itself. I propose to add a configuration parameter Gas to take the default value of dynamic configuration when adding a custom chain, such as 90000 or more. The reason is that our current plain transfers and IBC transfers have exceeded threshold of 80,000. If it cannot be added, it will generate a lot of unnecessary trouble and communication when users manually modify transfers.

![origin_img_v2_ea92d1ff-a23d-42ea-ba57-884a2992e66h](https://user-images.githubusercontent.com/8182002/178704077-4c9da19b-5e37-4e44-bee8-e8b33d889662.jpg)

**Describe the solution you'd like**
```
A clear and concise description of what you want to happen.
keplr.experimentalSuggestChain({
    ......
    Gas: value
})
```

**Describe alternatives you've considered**
Null

**Additional context**
Null

**Comment by zccst** [comment]
> 

Thanks for your prompt response. Do you have an expected publish date for new version

**Comment by Thunnini** [comment]
The most urgent goal is dark mode support in mobile app. After that, we will implement the auto gas estimation feature. If all goes well, I expect it to be around next Friday, but I can't be sure.

**Comment by Thunnini** [comment]
Gas estimation is supported on v0.10.14 now.
