### ISSUE TITLE
Config useEthereumAddress for suggest chain

### ISSUE THREAD

**Issue by hanhbd1** [chainapsis/keplr-wallet#453]
I see on v0.10.5 keplr auto detect chain that use ethereum Address when `coinType==60`.
But in latest version it become to using `useEthereumAddress` value.
So how I can change it on myown custom chain.

Thanks

**Comment by Thunnini** [comment]
After manually deleting the previously registered chain in chain selector, add "eth-address-gen", "eth-key-sign" to features and register it again.

**Comment by hanhbd1** [comment]
Thanks you so much
