### ISSUE TITLE
Juno APR is wrong!

### ISSUE THREAD

**Issue by chmichael** [chainapsis/keplr-wallet#457]
Hello,
  Juno APY/APRis wrong! Juno discord reports 72.07% (the correct) while Keprl 87.58%!
  
  Thank you

**Comment by Thunnini** [comment]
Do you know the formula for juno APR?

**Comment by bilalkhan360** [comment]
(inflation/staked Juno)*98

Current inflation=25,961,297.03

**Comment by chmichael** [comment]
@Thunnini Here's the APR (not APY) :)

![juno-apr](https://user-images.githubusercontent.com/13120950/179360470-5e40af61-5a21-424f-84f8-a603d11c0fa2.jpg)
