### ISSUE TITLE
Gas fee not considered when staking max available amount

### ISSUE THREAD

**Issue by brandoncomer** [chainapsis/keplr-wallet#460]
**Describe the bug**
When trying to stake the max amount available for any native token, gas fees are not considered when calculating the max amount. It used to do this before the design update. 

**To Reproduce**
Steps to reproduce the behavior (Stargaze as example:
1. Go to Stargaze chain in Keplr dashboard. 
2. Click on stake.
3. Click max amount and click Delegate button.
4. Keplr tx approval window will pop up with an "insufficient available balance for transaction fee" notice.

**Expected behavior**
When clicking the max button, the calculated amount should be the total wallet balance minus the low (or average if you prefer) gas fee.

**Screenshots**
<img width="672" alt="image" src="https://user-images.githubusercontent.com/90658712/179440244-31a0d4b6-9460-4451-a8d9-7b65f0800f7d.png">

<img width="354" alt="image" src="https://user-images.githubusercontent.com/90658712/179440325-32781eb6-2c66-430c-b864-0dd31ff4e78e.png">

**Device details (please complete the following information):**
 - OS: OS X
 - Browser: Chrome
 - Keplr Version: 0.10.12
 - Hardware Wallet: N/A

**Comment by delivan** [comment]
@brandoncomer This issue has been resolved. Thanks for the report.
