### ISSUE TITLE
ixo | Incorrect URL used for Stake button on Keplr Chrome extension

### ISSUE THREAD

**Issue by alwyn-ixo** [chainapsis/keplr-wallet#466]
**Describe the bug**
Given that someone uses the Keplr Chrome extension to stake IXO,
when they click the "Stake" button
then they encounter an error message - "Oops, We can't find this chain."

**To Reproduce**
1. Go to the Keplr Chrome extension on desktop and open the ixo mainnet chain.
2. Click on "Stake" which opens a browser window for "https://wallet.keplr.app/chains/impacthub".
3. See error "Oops, We can't find this chain."

**Expected behavior**
The browser window should open to "https://wallet.keplr.app/chains/ixo".

**Screenshots**
![image](https://user-images.githubusercontent.com/100694789/180196003-ddd58bad-bdef-47c7-8b0e-bb2fcd9829f0.png)

![image](https://user-images.githubusercontent.com/100694789/180195869-ec475a1c-8fc5-42c6-a10b-7999c5749a70.png)

![image](https://user-images.githubusercontent.com/100694789/180196100-c7303be0-a8a1-438e-a748-df6965c0f596.png)

**Device details (please complete the following information):**
Any OS on any type of device using the Chrome browser extension.

**Comment by Ryz0nd** [comment]
We've fixed this issue. Thanks!

**Comment by alwyn-ixo** [comment]
awesome, thx! 
I tested it now and it seems to work correctly - is anything further required or can I close this issue?

**Comment by Ryz0nd** [comment]
Sure! You can close it. 👍
