### ISSUE TITLE
desmos | Transaction Failed when trying to withdraw or deposit on Osmosis

### ISSUE THREAD

**Issue by lorenzomenegon** [chainapsis/keplr-wallet#468]
**Describe the bug**
A lot of Keplr users are facing this issue when trying to submit a transaction between Keplr and Osmosis with Desmos chain. The error message is the following:
> Transaction Failed: you have too many concurrent txs going on! Try resending after your prior tx lands on chain. (We couldn't send the tx with sequence number **0**)

**To Reproduce**
Steps to reproduce the behavior (not happening to every account):
1. Go to https://app.osmosis.zone/assets.
2. Click on Deposit button.
3. Sign the transaction.
4. See the error message posted in the description.

**Expected behavior**
The transaction should be correctly broadcasted. We already checked our RPC and everything is working fine. Seems like this is an issue with Keplr wallet.

**Screenshots**
![Screen_Shot_2022-07-06_at_9 21 37_AM](https://user-images.githubusercontent.com/106406454/180251929-32874376-1880-4532-959c-a948ff2e24d8.png)

**Device details (please complete the following information):**
 - OS: Monterey 12.4
 - Browser: Chrome 103
 - Keplr Version: 0.10.13
 - Hardware Wallet: No

**Additional context**
Users facing this issue do not have any transaction going on.

**Comment by Thunnini** [comment]
It seems to be related to osmosis frontend.

**Comment by lorenzomenegon** [comment]
@Thunnini Hones
the issue is also open on the osmosis frontend Repo, but honestly I think it's a Keplr problem. Other chains are also experiencing the same problem, and osmosis is not directly involved.

**Comment by lorenzomenegon** [comment]
Please note that the issue persists when initiating an IBC transfer directly via Keplr extension.
