### ISSUE TITLE
When the evmos chain is extended with keplr, the transfer is successful in the extension, but the transfer is wrong in the dapp (https://ping.pub)

### ISSUE THREAD

**Issue by YouquanWang** [chainapsis/keplr-wallet#470]
When the evmos chain is extended with keplr, the transfer is successful in the extension, but the transfer is wrong in the dapp (https://ping.pub)

Error: pubKey does not match signer address evmos1z9zk7an7zf8k7t5407yzsjky0n0scmr6hrzwu0 with signer index: 0: invalid pubkey

**Comment by Thunnini** [comment]
evmos has different way of generating addresses and this has to be handled by each website.
