### ISSUE TITLE
Wallet spam open on moving window [Minor]

### ISSUE THREAD

**Issue by Reecepbcups** [chainapsis/keplr-wallet#473]
**Describe the bug**
When opening the wallet.keplr.app page from a fresh browser (before sign in), if you move the window by the tab it will spam open the keplr extension up to 25/26 unique windows. (Video attached)

**To Reproduce**
1: Close all chrome instances (so it requires you to sign in w/ keplr)
2: Open chrome
3: Visit [wallet.keplr.app](https://wallet.keplr.app/chains/osmosis)
4: When the popup comes, move the window around.
5: Stops pushing new instances at 25/26 OR when you let go, which ever is first

**Expected behavior**
I would expect that when you drag the window, no more instances are brought up after the first.

**Video**
https://youtu.be/DkBYbVKYiNc

**Device details:**
 - OS: Manjaro 21.3.4 Ruah [x86_64 Linux 5.15.55-1-MANJARO]
 - Browser: Chrome Version 103.0.5060.53 (Official Build) (64-bit)
 - Keplr Version: 0.10.13

**Additional context**
This is a unique corner case, but have run into the issue 2 or 3 times now & is slightly annoying. It is possible it is something with my desktop environment, but I wanted to put here just in case.

**Comment by delivan** [comment]
@Reecepbcups Thanks for the report!

Keplr dashboard displays a window for chain connection approval for each chain to clearly show users which chain they are connected to. We currently support 24 chains, so 24 windows will pop up. However, many users should be annoying by many popups. Keplr team is figuring out a solution that makes it clear to the user which chains to connect to while approving the chain connection once and for all.

For now, my recommendation is
1. Sign in Keplr Wallet Extension in advance
2. Use a browser where a session is maintained, not a fresh browser(if the browser is a new session, popups will appear again to confirm the chain connection).

I think there are many reasons why you are using a fresh browser and you need that. So we will figure out how to make one popup enough.

**Comment by HS-Joe** [comment]
@delivan so is there a solution to get a wallet address without making the windows pop? I can see you guys manage to do it on https://wallet.keplr.app/ (wallet address is displayed top right without any connection request, and no connection is registered in Settings -> Manage Connections).
