### ISSUE TITLE
Link to Keplr Dashboard for staking even if all your funds are staked

### ISSUE THREAD

**Issue by trentagoric** [chainapsis/keplr-wallet#475]
If all your funds are staked, the "Stake" button becomes disabled; which results in no UI to access the Keplr dashboard for managing validators / existing staked tokens.

Ideally, there should be a "Manage" button or link to the Keplr dashboard under staking even all your funds are staked so you can manage existing staked tokens.

The current alternative is to find the wallet url, and bookmark it which is not ideal and may be impossible for some people to find.

**Comment by Thunnini** [comment]
The "Stake" button has been modified so that it is always enabled. Another issue for changes to the UI will be created later.
