### ISSUE TITLE
Secret Network chain_id is "secret" instead of "secretnetwork"

### ISSUE THREAD

**Issue by HS-Joe** [chainapsis/keplr-wallet#479]
**Describe the bug**
When calling `getKey` with `secretnetwork` chainId (as described in cosmos directory), the call fails with `Error: There is no chain info for secretnetwork`.
With argument `secret` is works correctly.

**Expected behavior**
As specified in https://chains.cosmos.directory/ the correct chainId is `secretnetwork` and not `secret`. We could add both in Kelpr code to keep backward compatibility.

**Comment by HS-Joe** [comment]
Eratum... actually not true, it just seems that there is some undocumented feature where passing the chainId without the digit works fine (which is great),

**Comment by sheriff-rango** [comment]
I have got a similar issue.
When I tried to get `account` using `getAccounts`  on `Mars Hub`, I got the error `Error: There is no chain info for mars-1`.
The chainId for `Mars` chain is `mars-1` and it works properly on browser but I got this error only on mobile.
