### ISSUE TITLE
Unbonding assets are not included in total asset value

### ISSUE THREAD

**Issue by joe-bowman** [chainapsis/keplr-wallet#485]
**Describe the bug**
When assets are unbonding, they are not included in the 'Total Asset Value' calculation.

**To Reproduce**
1. View 'Total Asset Value' on the dashboard
2. Unbond from any chain
3. Total Asset Value is now lower than expected.

**Expected behavior**
Unbonding delegation value should be included in 'Total Asset Value'

**Comment by delivan** [comment]
@joe-bowman Thanks for the report. We will fix it soon.

**Comment by delivan** [comment]
@joe-bowman It's fixed!
