### ISSUE TITLE
https://lcd-impacthub.keplr.app not available

### ISSUE THREAD

**Issue by alwyn-ixo** [chainapsis/keplr-wallet#486]
Apologies if this is not the correct repo for this issue - I could not find a better alternative.

**Describe the bug**
https://lcd-impacthub.keplr.app is no longer available.
https://github.com/search?q=org%3Acosmos+lcd-impacthub&type=code
It is listed in the Cosmos repo in these 3 places:
1. https://github.com/cosmos/chain-registry/blob/a9e81cab3de2cf0eb870f408a7f530fe34b3ad17/impacthub/chain.json
2.  https://github.com/cosmos/groups-ui/blob/f699783aca1533f8076709c7bc32419c2aa59c7e/src/components/chain-selector/chain-list-provider.ts
3. https://github.com/cosmos/composer/blob/5d83739d013d9340c72f8a45315e4a9682bf8ec5/react/src/types/settings.ts
For example:
```
{
        rpc: "https://rpc-impacthub.keplr.app",
        rest: "https://lcd-impacthub.keplr.app",
        chainId: "impacthub-3",
        chainName: "ixo",
        coinDenom: "ixo",
        coinMinimalDenom: "uixo"
    },

```

**Comment by Thunnini** [comment]
We didn't commit the endpoint to that repo in the first place. Posted by someone who has nothing to do with us.

**Comment by alwyn-ixo** [comment]
@Thunnini Thank you for the response.
Can you connect me with the team who would have posted that endpoint?
Or, when can I find them; Discord, GitHub, some other group?
I believe it may be the Chainapsis validator team; correct?

**Comment by Thunnini** [comment]
No. As far as I know, our internal team didn't put the endpoints in that repo. Since we didn't post it, we have no obligation to manage that endpoint well.
