### ISSUE TITLE
Importing a 'Private Key' returns an error about 'Too short mnemonic'

### ISSUE THREAD

**Issue by X-Tyler** [chainapsis/keplr-wallet#487]
**Describe the bug**
Importing a 'Private Key' returns an error about 'Too short mnemonic', which doesn't make sense to me.
A private key is not a mnemonic... 

**To Reproduce**
1. Go to 'Add Account' > 'Import Existing Account'
2. Select 'Private Key' from the dropdown
3. Enter the private key (not the mnemonic)
4. Click 'Next'
5. Error returned as 'Too short mnemonic'.

Note: Preliminary steps to reproduce may involve exporting the raw private key from terra station. cf. information in "Additional context".

**Expected behavior**
2 possible expected outcomes based on actual implementation of the functionality:
- **Keplr expects a private key**: for some reason Keplr considers my private key as invalid and should return clear error about that, unrelated to mnemonics.
- **Keplr expects a mnemonic**: Doesn't make sense, should process the actual raw private key instead.

**Screenshots**
<img width="537" alt="image" src="https://user-images.githubusercontent.com/92860290/184331862-48e3e423-9f99-4b27-82b2-93b83a138834.png">

**Device details (please complete the following information):**
 - Browser: Chrome Version 104.0.5112.81 (Official Build) (64-bit)
 - Keplr Version: 0.10.16

**Additional context**
I have a terra wallet that was created with Terra Station and allowed for a corrupted mnemonic (two repeated words). I would like to migrate my terra wallet to Keplr. But Keplr doesn't accept importing "invalid" mnemonic (based on RFC or alike). I was then hoping to import the raw private key, but it is still not possible at the moment.

**Comment by Thunnini** [comment]
Terrastation is not compatible with keplr because it returns the encrypted data with its own spec for private key. Contact terrastation and decrypt the private key and import it.

**Comment by X-Tyler** [comment]
Still, as stated above, I would then expect:
"Keplr considers my private key as invalid and should return clear error about that, unrelated to mnemonics."
Are we really good to close this bug report?

**Comment by X-Tyler** [comment]
Btw, documentation on importing private keys is really poor, and I believe the import Private Key screen should be a bit more verbose on what it expects. 

Afaik, Keplr only allows exporting private keys for accounts created with a Google account. I could actually confirm that I was able to import the Private Key of a freshly created Google account; So the functionality indeed doesn't expect a mnemonic but a 64 characters long private key. 

That said- considering I would manage converting my terra wallet into that format - will Keplr allow importing a private key that was not created with a Google account?

**Comment by Thunnini** [comment]
The private keys created with Terra station are encrypted using their own unique technical way. Keplr does not have any plans to support decryption for the specific way they are using to encrypt. 

Per the main issue stated in this issue of displaying as "too short mnemonic", on the second look, I do think that it is a valid bug, would get it fixed asap!

tbh, I don't really have much understanding on how you want or what you want to do with the wallet you've created with terra station, but I recommend you try importing with the mnemonics. (repeated words aren't classified as corrupted mnemomics in the Keplr extension, they should be no problem) If you are trying to use Terra classic, try adding the chain via wallet.keplr.app(add terra classic button). If its the new Terra chain you want to add, try adding it using app.osmosis.zone.

**Comment by rak16** [comment]
Hi there, I am facing the same issue here. Based on the conversation here, is it possible to convert the private key from Terra station to a format compatible with Keplr?
