### ISSUE TITLE
Hide gov proposals until a certain deposit threshold

### ISSUE THREAD

**Issue by haasted** [chainapsis/keplr-wallet#488]
It seems spammers / phishers may have found the governance mechanism on Osmosis, notably governance proposal 300 which seems to advertise a Juno 2.0 chain. It currently has a deposit of 1uosmo, but is featured prominently in the list of proposals alongside the regular incentive adjustments etc.

**Describe the solution you'd like**

Do not show governance proposals indiscriminately. Add a filter to when it's displayed for everyone to see in the Keplr wallet, eg. by only showing proposals that are in their voting period or has some meaningful deposit.

**Comment by delivan** [comment]
proposals in deposit period are not shown now. Thanks for reporting this.
