### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by phenixalex31** [chainapsis/keplr-wallet#499]
![bug keplr](https://user-images.githubusercontent.com/112648119/187973127-79c9c5dd-2a9f-4fbd-bba1-7cea5500930e.jpg)
Hello,

yesterday when I installed the wallet and the dashboard, everything was working, today it crashes all the time.
I tried a lot of manipulation, remove all the cookies...
reset 80% my browser, test brave .
each time the same error which crashes the application.
I think it's javascript that is not executing.

Can someone help me

thank you

ps: I very week

**Comment by delivan** [comment]
@phenixalex31 Thanks for the report. It's fixed now.

**Comment by phenixalex31** [comment]
incredible, I logged in, and the problem was gone, Delivan you are a magician, for me (even if I understand that it is programming language and code). too strong !!!!!
thank you very much.

ps: I also have a problem on the Terra station application, when I click to take my rewards each time it puts me "transaction is not available at the moment" 1 day I try but it does not work.

**Comment by xlightwaverx** [comment]
![Screenshot from 2022-09-30 15-00-43](https://user-images.githubusercontent.com/51795889/193339034-e26ab361-5955-41ce-84e0-76d7cc94245c.png)

Having similar issues as of this morning.  Clearing temp files/cookies seems to no avail.

Any suggestions?

Thank you.
