### ISSUE TITLE
Desmos | Fail to send token: account sequence mismatch

### ISSUE THREAD

**Issue by lorenzomenegon** [chainapsis/keplr-wallet#500]
**Describe the bug**
A lot of users are facing this issue when trying to submit a Send transaction between Keplr and another Keplr wallet with Desmos chain. The error message is the following:

> Fail to send token: account sequence mismatch, expected 6, got 0: incorrect amount sequence. 

IBC transfers are failing too, so looks like $DSM are stuck inside the wallet. Other wallets are currently working so i assume it's a Keplr issue.

**To Reproduce**
Steps to reproduce the behavior (not happening to every account, most of the times is for non-ledger accounts):

Open Keplr (Desmos chain)
Click on Send button.
Fill in and sign the transaction.
See the error message posted in the description.

**Expected behavior**
The transaction should be correctly broadcasted.

**Screenshots**
<img width="353" alt="Schermata 2022-09-01 alle 17 07 19" src="https://user-images.githubusercontent.com/106406454/187967630-6f137a20-c753-41b5-ae0b-6b377e1721d1.png">

**Device details:**
 - OS & Version: OS Monterey 12.4
 - Browser: Brave [Versione 1.42.97 Chromium: 104.0.5112.102 (Build ufficiale) (arm64)](https://brave.com/latest/)
 - Keplr Version: 0.10.20
 - Hardware Wallet: N/A
 
 **Backtrace**
This was marked as a Keplr issue from Osmosis front-end team: https://github.com/osmosis-labs/osmosis-frontend/issues/704

**Additional context**
An issue had already been opened, not being able to deposit from Keplr to Osmosis. After numerous tests and user reports we have come to the conclusion that there must be something wrong with Keplr, because wallets like Cosmostation or Forbole x have no problems.  I know I'm annoying, but I'm trying to help users who have decided to support DSM and are using Keplr.
A thousand thanks.

**Comment by Thunnini** [comment]
What's your account address?

**Comment by lorenzomenegon** [comment]
desmos1prstc8m9mkm0jfe7hh3pdkd2ywgye8med037ar

**Comment by Thunnini** [comment]
This should be solved by now

**Comment by lorenzomenegon** [comment]
The problem continues to persist
