### ISSUE TITLE
Umee APR Incorrect After Upgrade

### ISSUE THREAD

**Issue by brandoncomer** [chainapsis/keplr-wallet#519]
**Describe the bug**
We recently upgraded Umee to sdk 0.46 which deprecates rpc and lcd in favor of grpc-web/gateway. This has changed some endpoints. This is currently affecting the APRs displayed on Keplr's Dashboard (you're currently using our inflation rate instead). 

To fix, you'll need to change the path for supply from `/cosmos/bank/v1beta/supply/{denom}` to `/cosmos/bank/v1beta1/supply/by_denom?denom=uumee`

**To Reproduce**
Go to the Dashboard and look at the APRs on Umee. 

**Expected behavior**
Should display an accurate APR considering bonding rates, not just the inflation rate. 

**Screenshots**
![Screen Shot 2022-10-01 at 7 15 53 AM](https://user-images.githubusercontent.com/90658712/193414151-9ccebf6e-aa90-4571-a6c0-46da303e8a59.png)

**Device details (please complete the following information):**
 - OS: OS X
 - Browser: Chrome latest version
 - Keplr Version: 0.11.6
 - Hardware Wallet: Ledger Nano X

**Additional context**

**Comment by delivan** [comment]
@brandoncomer Now It's fixed on Keplr Dashboard.

**Comment by delivan** [comment]
@brandoncomer It's fixed on Keplr Wallet too.
