### ISSUE TITLE
`@cosmjs/launchpad` is unmaintained and deprecated

### ISSUE THREAD

**Issue by pyramation** [chainapsis/keplr-wallet#521]
@cosmjs/launchpad is unmaintained and deprecated, we should upgrade cosmjs.

many types from `@cosmjs/launchpad` are in `@cosmjs/amino` or `@cosmjs/proto-signing` now.

Ideally would be great to upgrade to 0.29.

**Comment by Thunnini** [comment]
Overall I agree with this issue.
However, keplr lacks motivation to update cosmjs for the following reasons.
 - Most of the parts used in keplr are typing or core logic that makes sign doc. This logic is not updated often.
 - The typing of cosmjs is not actively updated and does not reflect the latest cosmos-sdk's feature. (Keplr does not support all the latest features either.)

But this issue is right. We will update it soon.

**Comment by pyramation** [comment]
Thanks @Thunnini !!

If you're interested in some details aside from the unmaintained and deprecated parts:

Actually the main motivation is that due to changes in recent additions of cosmjs, if you use the wallet-connect for keplr mobile (as in [cosmos-kit](https://github.com/cosmology-tech/cosmos-kit)) — keplr-wallet wallet-connect will pull in an old version of cosmjs, and therefore provide mismatched types.

Effectively when you begin to create custom signers with amino encoding registries, and proto encoding registries, if you use cosmos-kit (or keplr-wallet wallet-connect), you end up getting strange errors as a result of bad npm resolutions.

**Comment by keupsonite** [comment]
+1

**Comment by Thunnini** [comment]
@pyramation @keupsonite Hey, I removed @cosmjs/* from dependencies. I expect that it can solve your problems. And, it is published with version 0.11.16-alpha.0
Can you check that the problems are fixed with 0.11.16-alpha.0?

**Comment by pyramation** [comment]
So far looking good!

I did notice one think in the `yarn.lock`, all of the required cosmjs packages were up to date, except for one:

[here is a comment so you can see where](https://github.com/chainapsis/keplr-wallet/commit/1fae575c814f39d374404742cf661d2815c313a6#r88706715)

```
"@cosmjs/crypto@^0.24.0-alpha.25", "@cosmjs/crypto@^0.29.3"
```

**Comment by Thunnini** [comment]
`@cosmjs/stargate` exists for compatibility testing with cosmjs. However, packages uploaded to npm do not have @cosmjs/* as a dependency. However, it seems that secretjs has a part of @cosmjs as a dependency. We will also remove secretjs itself later. But now, I have a part of @cosmjs/* indirectly by secretjs, so I don't know if this will be a problem or not.

**Comment by pyramation** [comment]
ok great, sounds good!

**Comment by pyramation** [comment]
@Thunnini thanks a lot for doing this PR! I'm super grateful and appreciative! 

So far removing launchpad and cosmjs/* has cleaned up many deps! This is great! 

We're already using `0.11.16-alpha.0` in production for [`chain-registry`](https://github.com/cosmology-tech/chain-registry) and also [`cosmos-kit`](https://github.com/cosmology-tech/cosmos-kit)

**Comment by Thunnini** [comment]
0.11.16 is published to npm. You can use +0.11.16 version.
