### ISSUE TITLE
Failed to save profile picture

### ISSUE THREAD

**Issue by EmperorTheFirst** [chainapsis/keplr-wallet#535]
When trying to set an NFT as profile picture I always get an error 'failed to save profile picture' after signing the tx for proof of ownership. I'm obviously the owner but after trying for over a day still the same error. This is in the newer version of Keplr. classic version doesnt show the NFT at all

**Comment by delivan** [comment]
@EmperorTheFirst Thanks for reporting that bug. It has been fixed!
