### ISSUE TITLE
Use chain config `gasPriceStep` as fallback if one is not set in `feeCurrencies`?

### ISSUE THREAD

**Issue by williamchong** [chainapsis/keplr-wallet#536]
**Is your feature request related to a problem? Please describe.**
We are using `experimentalSuggestChain` to add [LikeCoin chain](https://like.co/) into Keplr for our [dApp](https://liker.land) users

Since https://github.com/chainapsis/keplr-wallet/commit/bbb388c061f485e2d36f2ab7f04d2b1b5362d848 , `gasPriceStep` was moved into `feeCurrencies`. This change makes Keplr fallback to the default `0.01,0.025,0.04` step for ALL our existing user with the old config. In our chain we requires `1,10,1000` for transactions to pass, the default gas step would cause timeout.

We have since update our config to put `gasPriceStep` into `feeCurrencies`, but there is not way for us to force update users chain config using `experimentalSuggestChain`. We are getting reports everyday related to transaction timeout, which potentially causes user to drop out of our dapp.

**Describe the solution you'd like**
If  `gasPriceStep` is not set in `feeCurrencies`, but exists in config root as in the old spec, can we fallback to use the `gasPriceStep` in root?

**Describe alternatives you've considered**
Alternatively, `experimentalSuggestChain` should allow me to force update a user's chain configuration, if theirs is outdated.

**Additional context**
Users cannot send transactions since keplr set a default gas price lower than what we expect, when user has an old configuration where `gasPriceStep` is in the root of chain config:
<img width="570" alt="Screenshot 2022-10-18 at 3 50 17 PM" src="https://user-images.githubusercontent.com/6198816/196371414-d6b7f94a-433e-4eef-8481-b506d81ab9ab.png">

We have updated our config as per the new spec, but we cannot force update it to users, so they are still getting timeout everyday:
https://github.com/likecoin/mainnet/pull/6
https://github.com/likecoin/like-co/pull/1666
https://github.com/likecoin/likecoin-wallet-connector/pull/8

**Comment by Thunnini** [comment]
Sorry. I understand your difficulties. I'll fix this temporarily. 
Sooner or later, chain infos will be managed in one Github repo. Then there will be no such problems.

**Comment by Thunnini** [comment]
New version is pending review on chrome webstore. I will notice you when it is published

**Comment by Thunnini** [comment]
@williamchong It is published now. If the problem is not solved, please reopen the issue.
