### ISSUE TITLE
@keplr-wallet/types requires axios@0.21.1 via secretjs@0.17.5 which has a security vulnerability.

### ISSUE THREAD

**Issue by srinivas-gangaraju** [chainapsis/keplr-wallet#539]
axios before v0.21.2 is vulnerable to Inefficient Regular Expression Complexity.
This is being used in secretjs@0.17.5 version. They have fixed this vulnerability in latest version of secretjs from 1.4.0
can u also fix this issue by upgrading your secretjs dependency.

https://deps.dev/npm/secretjs/0.17.8
https://deps.dev/npm/secretjs/1.4.0

**Comment by cnotethegr8** [comment]
I would also like this fixed to resolve my repos security alerts.

It appears that `@keplr-wallet/types` only needs the `SecretUtils` interface, and nothing more.
This interface exists in `secretjs@0.17.*` but as far as I can tell, does not exist in `secretjs@1.*`.

A simple solution would be to just take this interface, add it to `@keplr-wallet/types`, and remove the `secretjs` dependency.

```typescript
export interface SecretUtils {
  getPubkey: () => Promise<Uint8Array>;
  decrypt: (ciphertext: Uint8Array, nonce: Uint8Array) => Promise<Uint8Array>;
  encrypt: (contractCodeHash: string, msg: object) => Promise<Uint8Array>;
  getTxEncryptionKey: (nonce: Uint8Array) => Promise<Uint8Array>;
}
```

**Comment by Thunnini** [comment]
#563 makes @keplr/types not include secretjs.
And, we have a plan to migrate from axios to fetch for manifest v3.
