### ISSUE TITLE
Fix Juno apr Formula on Keplr dashboard

### ISSUE THREAD

**Issue by bilalkhan360** [chainapsis/keplr-wallet#543]
This is the formula for calculating Juno apr

(inflation/staked Juno)*98

Current inflation= 25,961,297.03 

Inflation after halving tomorrow = 18,172,908

the keplr dashboard shows 77.64% while the current apr is 58.42%

**Comment by iam-agf** [comment]
Where does the `98` comes from in `(inflation / stake Juno) * 98 `

**Comment by bilalkhan360** [comment]
> 

2% is community tax ```100-2 = 98```

**Comment by delivan** [comment]
It is resolved! Thank you for reporting the issue.
