### ISSUE TITLE
Verify signatures for arbitrary messages

### ISSUE THREAD

**Issue by emperorjm** [chainapsis/keplr-wallet#560]
Based on the following docs https://docs.keplr.app/api/#request-signature-for-arbitrary-message verification can be done using the verifyArbitrary API or the verifyADR36Amino function from the @keplr-wallet/cosmos package.

I am currently using a PHP backend and want to find out what would be the requirements for verifying these arbitrary signatures outside of the Javascript solutions above.

**Comment by Thunnini** [comment]
https://github.com/chainapsis/keplr-wallet/blob/master/packages/cosmos/src/adr-36/amino.ts#L119
https://github.com/cosmos/cosmos-sdk/blob/main/docs/architecture/adr-036-arbitrary-signature.md

You can check above links.
You should make sign doc comprised of ADR-036 spec. And, verify that with scep256k1 signature after hashing it by sha256.
