### ISSUE TITLE
Error: Keplr wallet does not update amount of tokens on Sifchain

### ISSUE THREAD

**Issue by intercos** [chainapsis/keplr-wallet#568]
**Describe the bug**
Keplr wallet incorrectly displays token amount on Sifchain
But, It is displayed normally in "Sifchain Dex or www.mintscan.io".

**To Reproduce**
Send or swap tokens in Sifchain
receive IBC tokens from another chain.

**Error Cause**
It seems that Keplr is not reading the current block data on Sifchain 
and are reading the old block data on Sifchain

**Expected behavior**
The Keplr wallet should display the amount of tokens in the current block data on the Sifchain.

**Screenshots**
![keplr Err sif](https://user-images.githubusercontent.com/94884108/202826805-e5f07489-e65f-4868-b769-d957bdeaa8aa.jpg)

**Device details (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome Version 107.0.5304.107
 - Keplr Version: 0.11.17
 - Hardware Wallet:

**Comment by intercos** [comment]
![sif err2](https://user-images.githubusercontent.com/94884108/202932621-f084bac6-9f57-4ef0-acf3-0013c9164ffc.jpg)
After 2 days have passed, 
Keplr will display the amount of tokens swapped before.
That is, Keplr reads the block data from 2 days ago, not now.

**Comment by Thunnini** [comment]
Ditto with #569
