### ISSUE TITLE
Ledger Signing on SEI network

### ISSUE THREAD

**Issue by ELZ-CB4** [chainapsis/keplr-wallet#570]
**Describe the bug**
Trying to sign a transaction on SEI network with a ledger result in a "Data is Invalid : Unexpected characters" error.

**To Reproduce**
1. Create a transaction on Vortex for exemple (it works to send tokens in Keplr)
2. Try to sign

**Device details (please complete the following information):**
 - OS: Windows
 - Browser: Brave [Version 1.45.127 Chromium: 107.0.5304.110](https://brave.com/latest/)
 - Keplr Version: 0.11.17
 - Hardware Wallet: Ledger

**Comment by Thunnini** [comment]
Ledger does not support proto signing, please use Amino signing instead.
