### ISSUE TITLE
Extension allowable fee currencies flexibility

### ISSUE THREAD

**Issue by ChristianBorst** [chainapsis/keplr-wallet#572]
Description: The Keplr browser extension should allow websites to suggest more fee tokens. For Gravity Bridge in particular users would ideally pay their fees in the tokens they are using on the bridge, e.g. paying some ATOM to the chain when bridging to and from Ethereum.

Desired Solution: Chains like Gravity should be able to have an opt-in, more flexible fee option. In particular, user interfaces like bridge.blockscape.network could suggest a fee denominated in ATOM or WETH.grv, etc. depending on what the user is doing. If a user is bridging USDC from Ethereum, interacting with exchanges like Crescent, and trying to return their funds to Ethereum, they should be able to pay a fee in terms of USDC.

Alternatives: We have considered allowing fees in terms of GRAV and other tokens, but this would limit users in their attempts to return funds to Ethereum. For example with a user trying to use canto.io (whose users are mainly Ethereum users unfamiliar with Cosmos), they can successfully get funds onto Canto without issue but returning to Ethereum is a pain. They first have to identify an exchange where they can buy the fee token for the tokens they currently have (which may not exist), IBC transfer funds, interact with that exchange, IBC transfer the fee token back to Gravity and finally they can try to complete their bridge. 

Context: The Gravity community has recently voted to enable a system of bridging fees in this proposal: https://www.mintscan.io/gravity-bridge/proposals/86
When we tried to implement fees with our partner Blockscape, Keplr rejected the suggested fees with odd behavior.

**Comment by Thunnini** [comment]
Maybe duplicated #571
