### ISSUE TITLE
Error: Data is invalid : Unexpected characters when using Ledger

### ISSUE THREAD

**Issue by 0xArbi** [chainapsis/keplr-wallet#584]
**Describe the bug**

Unable to submit text proposals on any network via https://proposals.subtract.fi or https://commonwealth.im when using Keplr connected to a Ledger. Both sites work when using a seed phrase based Keplr account.

The exact error is 

```
Error: Data is invalid : Unexpected characters
    at r (injectedScript.bundle.js:10:37633)
```

**To Reproduce**
1. Go to `https://proposals.subtract.fi/?chain=stargazetestnet`
2. Make a fake text proposal
3. Submit

Keplr is never even opened to allow signing.

**Expected behavior**
Keplr opens and we are able to sign the transaction.

**Device details (please complete the following information):**
 - OS: OSX
 - Browser: Chrome & Brave
 - Keplr Version: 0.11.21
 - Hardware Wallet: Ledger Nano S & Ledger Nano X

**Comment by Thunnini** [comment]
This error is not from keplr but from ledger nano. Cosmos app on ledger nano supports only amino sign doc. Webpages should use `signAmino()` for ledger support.

**Comment by 0xArbi** [comment]
I see, thank for clarifying
