### ISSUE TITLE
Governance doesn't show which proposals voted by me

### ISSUE THREAD

**Issue by Petr-Mi** [chainapsis/keplr-wallet#592]
On page of proposals does not show which proposals were voted by me.

Win10 x64, Chrome v108.0.5359.99

**Comment by Thunnini** [comment]
When governance is past voting period, the voting records get deleted on chain. The dashboard only uses onchain queries, so when the voting period ends, it cannot be queried anymore. Therefore, its not a bug.
If we want to establish the feature u are talking about, we need a separate backend, but we dont have specific plans for this yet.
