### ISSUE TITLE
Terra Classic Bug Fees

### ISSUE THREAD

**Issue by andimiftahuddin** [chainapsis/keplr-wallet#596]
Bug Fees on Terra Classic Netwok (beta)

Reproduce:
1. Send Luna Classic
2. Whetever level fees (low, average, high)
3. Error "Fail to send token: insufficient fees;"

Screenshot:
![image](https://user-images.githubusercontent.com/50323142/206917694-3ed6645c-cb69-45f2-9e5b-d124571bfa19.png)

Device:
Chrome Keplr Extensions
Windows 8.1

**Comment by Thunnini** [comment]
Terra classic is not officially supported. It just means that Keplr is not compatible with terra classic and it is not a bug. We don't have any plan to support terra classic.
