### ISSUE TITLE
Displaying the voting status for proposals that have not yet been closed does not work

### ISSUE THREAD

**Issue by xjmecrypto** [chainapsis/keplr-wallet#598]
**Describe the bug**
Displaying the voting status for proposals that have not yet been closed does not work (stopped working).

**Expected behavior**
It should be stated (un)voted proposal (within not closed proposals).

**Screenshots**
Screenshot of Keplr wallet about opened proposals:
![image](https://user-images.githubusercontent.com/120336920/206926342-dd0eed06-2dae-4635-83c7-f24086ad9acb.png)

Screenshot of Votes section from https://www.mintscan.io/ (to prove that a vote was taken).
![image](https://user-images.githubusercontent.com/120336920/206926318-3319a311-e78f-42cb-b55d-34989683717d.png)

**Device details (please complete the following information):**
 - OS: Windows
 - Browser: Chrome Version 108.0.5359.99 (Official Build)
 - Keplr Version: 0.11.23
 - Hardware Wallet: Ledger Nano X Firmware version 2.0.2

**Additional context**
It was functional until recently, but unfortunately I don't know when exactly it stopped working.

**Comment by Petr-Mi** [comment]
Great! It's working now. :-)

**Comment by delivan** [comment]
Hey @xjmecrypto, voting status is kept on chain only during the voting period so It needs to be saved in an external database to fully support that. Keplr team is figuring out how to solve this problem so It will be fixed in the near future. Thanks for reporting this issue.
