### ISSUE TITLE
Extension context invalidated

### ISSUE THREAD

**Issue by husamia** [chainapsis/keplr-wallet#603]
From https://restake.app/ when connect to Keplr Wallet I get the error:

Failed to connect to Keplr Extension: Extension context invalidated.
![Screen Shot 2022-12-18 at 10 52 24 AM](https://user-images.githubusercontent.com/13439952/208307386-4c56112c-b501-43ef-9608-06f206778bd1.jpg)

I expected to connect with no errors.

 - Browser: Chrome Version 108.0.5359.124 (Official Build) (x86_64)
 - Keplr Version: Version 0.11.26 ID dmkamcknogkgcdfhhbddcghachkejeap

**Comment by Thunnini** [comment]
This error occurs when the extension is refreshed or updated automatically or manually.
This error is generated by the web browser and cannot be handled by the extension. There is no solution other than for the user to refresh the webpage.

**Comment by husamia** [comment]
> This error occurs when the extension is refreshed or updated automatically or manually. This error is generated by the web browser and cannot be handled by the extension. There is no solution other than for the user to refresh the webpage.

I refreshed the webpage and the extension wallet was recognized. Thank you
