### ISSUE TITLE
where is the source code of keplr dashboard

### ISSUE THREAD

**Issue by 04-26** [chainapsis/keplr-wallet#605]
I am a developer, I would like to ask where is the source code of keplr dashboard?

**Comment by Thunnini** [comment]
Keplr dashboard is not open source.

**Comment by 04-26** [comment]
> Keplr dashboard is not open source.

ok, thanks for replying.  I would like to ask how the Keplr dashboard obtains the address of the wallet？

**Comment by Thunnini** [comment]
You can check https://docs.keplr.app/
