### ISSUE TITLE
Verifying "signArbitrary" from rust.

### ISSUE THREAD

**Issue by MartianGreed** [chainapsis/keplr-wallet#611]
Hey, I have a frontend application that sign some data on frontend. Now I want my backend to check the correctness of the signature is there a way to do this in rust or I have to implement a full solution on my own ?
In advance thank's !

**Comment by HeesungB** [comment]
Can you refer to the link below?

https://github.com/chainapsis/keplr-wallet/blob/master/packages/cosmos/src/adr-36/amino.ts

**Comment by MartianGreed** [comment]
Thank's I'll dig into it

**Comment by MartianGreed** [comment]
I've had some time today to work on [this](https://github.com/MartianGreed/rust-verify-keplr-signature) tell me if this seems ok to you ?
