### ISSUE TITLE
How to list out IBC Tokens from balance in Tokens View (Keplr Extension)

### ISSUE THREAD

**Issue by akhilkumarpilli** [chainapsis/keplr-wallet#617]
I am running a local testnet and tried to add it to Keplr extension. I can view balance of staked denom but not able to view ibc tokens balance. 

Is there any way that tokens view will be updated dynamically based on IBC tokens in balance? What's the process I need to do to make it work?

**Comment by HeesungB** [comment]
@akhilkumarpilli 
Could you give me an example in more detail?

**Comment by akhilkumarpilli** [comment]
![keplr1](https://user-images.githubusercontent.com/36399231/210733366-71cf81c2-f094-4262-aba5-91f9dbb1156d.jpg)

IBC tokens list is not showing here. My address has balance:
```
- amount: "200000"
  denom: ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2
- amount: "2000000"
  denom: utac
```

But In keplr, it only shows `utac`  balance as it is a staked denom. How can I list out IBC balances of address in keplr?

**Comment by sybilsingleton** [comment]
When this happens to me I can fix it by:
1) removing the testnet from Keplr
2) refreshing the page (very important)
3) connecting with keplr again

Afaik the `currencies` for `experimentalSuggestChain()` are only set when the page is loaded and not not dynamically pulled from the API.
