### ISSUE TITLE
Walletconnect Migrating

### ISSUE THREAD

**Issue by solitarysp** [chainapsis/keplr-wallet#619]
Version 1.0 Walletconnect is about to expire. When will we transition to version 2.0 ?

https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e

**Comment by dgabriele** [comment]
In this vein, can you guys update your keplr-wallet example app to perform the proper steps to connect via WalletConnect?

Seriously, guys. It's not cool that everyone has to reverse-engineer other people's experimental code to figure out over and over again how to perform the correct sequence of steps to create a stupid connect modal with Keplr extension and WalletConnect.

The lack of support literature is extremely frustrating.

**Comment by dgabriele** [comment]
I apologize for my cries of frustrated, but I finally stumbled upon the demo package for wallet-connect in the repo. I made a tiny Nextjs app, where I tried to implement only the critical path for approving a connection by launching Keplr Mobile's "connect" modal and then, upon returning to the browser, instantiating a signing client and fetching accounts. I'll make a repo for this tomorrow. It would be worth sharing it along side your existing demo project. In my opinion, it is imperative for the competitive success of Cosmos to provide this, or else a lot of developers will continue just giving up at a certain point.

**Comment by Thunnini** [comment]
I apologize for the delayed response.
Our current implementation of WalletConnect is using version 1, and we are utilizing the Keplr standard specification. However, it is not currently recommended as we plan to support multi-chain functionality with the release of WalletConnect v2.

I am uncertain of the exact plans for implementing WalletConnect v2 in our project, but it is currently under development and is expected to be released this month. Once it becomes available, I will provide instructions on how to use it.

**Comment by luca992** [comment]
@dgabriele they updated the cosmos walletconnect dapp example yesterday on this branch:

https://github.com/WalletConnect/web-examples/tree/refactor/cosmos-dapp-update/dapps/react-dapp-v2-cosmos-provider

cosmostation is working with walletconnect v2 if you want to get started porting

**Comment by dgabriele** [comment]
Awesome. Thanks man!

**Comment by luca992** [comment]
> Awesome. Thanks man!

I was playing with it yesterday and I realized I misunderstood a bit how walletconnect actually works. You technically could use it to sign transactions. But you won't have access to a `keplr` instance that works with walletconnect v2 until they update the `wc-client` [package](https://github.com/chainapsis/keplr-wallet/blob/master/packages/wc-client/src/index.ts). Just fyi to save you some time.

**Comment by solitarysp** [comment]
@Thunnini Thank you, please tell us when v2 is updated on main branch. <3 <3

**Comment by SmiteDeluxe** [comment]
@Thunnini I am quite new to implementing Keplr and ran into this issue of generally being unable to implement a WalletConnect connection for mobile in an Angular project, as it seems to not be natively integrated and all in all not really documented. The examples in code that I was finally able to find are for React so I wonder on the current state of the v2 migration before attempting to translate it to Angular.
Does this latest merge mean that the part that I would need is done? I am quite confused as I still see some "v1"s in especially the example, so would highly appreciate any help!
