### ISSUE TITLE
Suggest Chain feature doesn't support authenticated RPC requests

### ISSUE THREAD

**Issue by bfcoursewool** [chainapsis/keplr-wallet#636]
**Describe the bug**
RPC requests to a custom chain added with the experimental suggestChain feature fail if the chain requires authenticated requests, even when correct rpcConfig headers are passed to keplr via the ChainInfo object. The ChainInfo type declaration includes comments that indicate that the rpcConfig is deprecated, so this might simply be an unimplemented feature? Is that correct? 

**To Reproduce**
1.) Set up a Cosmos node with authenticated RPC requests required
2.) Create ChainInfo for that node, including rpcConfig with an auth header and access token
3.) Suggest the chain to Keplr
4.) Connect the wallet
5.) Initiate a transaction or simply do a balance check in the extension, and see "Missing Authentication Token" error, or simply that the transaction is declined due to no balance. Womp womp. 

**Expected behavior**
Custom chains should be configurable to allow rpc headers in the requests.

**Comment by HeesungB** [comment]
@bfcoursewool 
There was an issue related to the web socket headers, so we stopped supporting the feature. 
We currently do not have any plans to resume it.

**Comment by bfcoursewool** [comment]
@HeesungB -- Thanks for the quick reply! We've found a workaround that works, but it's good to have confirmation that we weren't missing something! Much appreciated.
