### ISSUE TITLE
Can not support NYM

### ISSUE THREAD

**Issue by LXHLeaner** [chainapsis/keplr-wallet#637]
I want the Keplr wallet to support the NYM chain:

How do I manually load mainnet Nym/nyx into Keplr?

The NYM chain transaction like this:
https://www.mintscan.io/nyx/txs/CE3A71A987179D4B655B8590334DB668138EF84BB8F8632EE439D85B5791DF8D

**Comment by LXHLeaner** [comment]
How do I manually load Nym/nyx into Keplr?

**Comment by HeesungB** [comment]
Could you regist [here](https://github.com/chainapsis/keplr-chain-registry)?
