### ISSUE TITLE
Claiming button for staking rewards doesn't work on Mars Hub

### ISSUE THREAD

**Issue by Traianoverse** [chainapsis/keplr-wallet#649]
Describe the bug:
The "Claim" button doesn't work from keplr dashboard on Mars Hub(https://wallet.keplr.app/chains/mars-hub).

Expected behavior:
It should be available as it does on the extension.

Screenshots of the issue:
![image](https://user-images.githubusercontent.com/109481864/217862774-10c35a88-d75d-42b3-b3c9-702dc6e7985e.png)
It does work on the extension:
<img width="558" alt="Schermata_2023-02-08_alle_11 45 33" src="https://user-images.githubusercontent.com/109481864/217863119-703a0a00-8568-42a9-97ce-be4a11fed771.png">
Device details (please complete the following information):

OS: Windows & macOS Monterey
Browser: Chrome Version 108.0.5359.99  &  Brave Version 1.45.123
Keplr Version: 0.11.23
Hardware Wallet: Ledger Nano X Firmware version 2.0.2

**Comment by delivan** [comment]
@Traianoverse Thanks for reporting this issue. It is fixed now :)
