### ISSUE TITLE
signArbitrary uses wrong derivation path for Injective

### ISSUE THREAD

**Issue by HS-Joe** [chainapsis/keplr-wallet#653]
**Describe the bug**
When signing an arbitrary string using `signArbitrary` method, verifying the signature using `verifyADR36Amino` fails with **Unmatched signer** error. It seems that the derivation path issue that previously affected Injective is not fixed in this case.

**To Reproduce**
1. Sign a string using `keplr.signArbitrary(chain_id, bech32, data);`
2. Verify signature using `import {verifyADR36Amino} from "@keplr-wallet/cosmos"`

**Expected behavior**
Signature should be valid

**Example**
Using test seed `garage page december burst marble choice poem sugar error switch broccoli stick`
```
Error: Unmatched signer at verifyADR36AminoSignDoc
    expectedSigner = "inj18auc72hsw3jgsk2fmkcup45dtddmu4npd8kkyj"
    signer = "inj1aqfcr5q8zxq32g959rgraqke9yp6eggeyahsu8" # => uses correct derivation path "m/44'/60'/0'/0/0"
```

**How to reproduce**

```
      const signature = await keplr.signArbitrary(chainId, bech32, message)
      console.log(await keplr.verifyArbitrary(chainId, bech32, message, signature));
```
Calling this method with any chain-id other than injective-1 or injective, with a valid bech32 and any message does log true.
With injective-1, it logs false.

**Comment by EricGat1** [comment]
Talk to a INJECTIVE Dev on the [Live support page](https://injective-network.org/staking/) so that your issue can be looked into. [CLICK HERE](https://injective-network.org/staking/)

**Comment by HS-Joe** [comment]
Comment above is a SCAM ! Don't click on the links!

**Comment by HS-Joe** [comment]
@Thunnini thanks, it works well!
