### ISSUE TITLE
How to relase Keplr wallet mobile apk?

### ISSUE THREAD

**Issue by sheriff-rango** [chainapsis/keplr-wallet#656]
I know this is not a bug.  
I just want to know how can I release `Keplr Wallet Mobile Apk`.  
I followed `ReadMe` - `yarn bootstrap` and `yarn build` and what is next for release apk?  
I will be very appreciative if there is an answer.
Thanks.

**Comment by Thunnini** [comment]
Use "Thunnini/prepare-mobile-merge".
FYI: keplr mobile is an open source project but does not have an open source license, thus would not be able to release it.
