### ISSUE TITLE
UI issue: Max button produces incorrect format (adds a comma) for SSCRT to SCRT conversion 

### ISSUE THREAD

**Issue by kobrien** [chainapsis/keplr-wallet#669]
URL = https://wallet.keplr.app/chains/secret-network?tab=convert

When you press the max button on large amounts a comma is inserted which results in the Convert button being greyed out, removing the comma from the amount in the textfield enables the convert button

![Screenshot 2023-02-21 at 12 49 14](https://user-images.githubusercontent.com/723824/220338139-5356d343-f550-4442-ae1d-4d5e0852a132.png)

**Comment by delivan** [comment]
@kobrien Thanks for reporting this issue. It's fixed now.
