### ISSUE TITLE
walletconnect v2 - `signDirect` error

### ISSUE THREAD

**Issue by ap-justin** [chainapsis/keplr-wallet#677]
**Describe the bug**
when requesting `cosmos_signDirect` to keplr gives this error
```json
{
    "code": 1,
    "message": "t.indexOf is not a function. (In 't.indexOf('-')', 't.indexOf' is undefined)"
}
```

**To Reproduce**
1. Go to [keplr standalone examples](https://react-app.walletconnect.com/) - ( used this as this has the same behavior with my dapp )
2. connect keplr mobile via QR 
(this should appear)
<img width="335" alt="image" src="https://user-images.githubusercontent.com/89639563/222913974-8b29a79d-cce3-4de9-9293-fd268a2d9602.png">

3. click `signDirect`

<img width="571" alt="image" src="https://user-images.githubusercontent.com/89639563/222913994-39eb6a3b-4128-45e4-81dc-6e53966aa990.png">

**Expected behavior**
1. clicking `cosmos_signDirect` should show approval prompt ( Trust wallet doesn't seem to have this issue )
![IMG_2464](https://user-images.githubusercontent.com/89639563/222914240-eeda56ca-05f4-47da-ad56-d73f56c5ded8.PNG)

**Screenshots**

**Device details (please complete the following information):**
 - OS: IOS 16.3.1
 - Browser: Chrome Version 110.0.5481.177 
 - Keplr Version: Keplr mobile App version 1.1.9 Build Number 74 Code Version v147

**Comment by Thunnini** [comment]
I was my mistake. I will publish fixed version soon.

**Comment by Thunnini** [comment]
However, it seems that example page of wallet connect uses legacy spec of cosmos. Keplr follows the current version of cosmos spec https://docs.walletconnect.com/2.0/advanced/rpc-reference/cosmos-rpc
So, it may not work on wc2 example page.

**Comment by ap-justin** [comment]
@Thunnini, thanks ser for the fix, I will try in our dapp and will give update

**Comment by ap-justin** [comment]
@Thunnini, I tested commit https://github.com/chainapsis/keplr-wallet/commit/06f0972a6418658c903300151f9c69b28bfb5c1d

but still encounter the same error with keplr. Kindly see this [sandbox](https://codesandbox.io/s/nervous-mayer-h7f9lz) where I tried to use this
> Keplr follows the current version of cosmos spec https://docs.walletconnect.com/2.0/advanced/rpc-reference/cosmos-rpc So, it may not work on wc2 example page.

the sandbox example also works for Trust wallet 
![IMG_2473](https://user-images.githubusercontent.com/89639563/223412766-7d912bce-a5c5-48f5-94b7-3877cd464580.PNG)

**Comment by williamchong** [comment]
Using the sample dapp in walletconnect github https://react-dapp-v2.vercel.app/
Keplr android app straight up crashes

**Comment by ap-justin** [comment]
UPDATE: tried to run sandbox again and `MsgSend` worked. Updating of mobile app may be necessary to catch the fix https://github.com/chainapsis/keplr-wallet/commit/06f0972a6418658c903300151f9c69b28bfb5c1d
