### ISSUE TITLE
Keplr doesn't remember form data after page loses and regains focus

### ISSUE THREAD

**Issue by jargoman** [chainapsis/keplr-wallet#678]
**Describe the bug**
When sending a payment using keplr the wallet is nearly unusable for users that copy and paste. 
Copying from another page will cause keplr to lose focus and "forget" all form data.

**To Reproduce**
1. initiate a payment
2. Paste receive address into recipient textbox
3. Copy memo from another tab (or same tab)
4. Keplr resets to home view and has forgotten the address pasted. 

**Expected behavior**
When I send orai from keplr wallet. I need to copy the address and memo (from exchange deposit page). I need to be able to switch focus from one browser tab (copy an address) then return to keplr wallet and paste (into textbox). I need to do this twice and keplr needs to remember the data I've copied. 

**Screenshots**
Applies to all pop down windows with text input (presumably all popdown tabs are effected)

**Device details (please complete the following information):**
 - OS: linux mint
 - Browser: Brave
 - Keplr Version: 0.11.44
 - Hardware Wallet: none

**Additional context**
The only solution for this problem for me is to copy the address using copy and paste. Then copy the memo manually.

Metamask solves this problem by allowing metamask to open in an separate tab which has "memory" which isn't reset after loosing focus.

**Comment by HeesungB** [comment]
@jargoman 
Press the button on the top right to send an Asset to a new window.
Do you think this will help?

<img width="363" alt="스크린샷 2023-03-09 오후 12 49 46" src="https://user-images.githubusercontent.com/32606183/223912057-bd183555-d1d2-4e26-8048-2600b152ff45.png">

**Comment by jargoman** [comment]
Omg thank you. I don't know how I missed that when I was specifically looking for an expand button. I know it seems like a small detail but I just lost $70 forgetting a memo

**Comment by HeesungB** [comment]
@jargoman 
Thank you for your good opinion.
I will refer to your opinion when improving the send page!
