### ISSUE TITLE
Incorrect phishing site detection 

### ISSUE THREAD

**Issue by siddharth-leap** [chainapsis/keplr-wallet#684]
Hey Folks, I am Siddharth, a developer from the leapwallet.io's engg. team. 

**Describe the bug**
We just discovered a few days ago that keplr extension is incorrectly detecting https://cosmos-wallet-demo.web.app/ as a phishing website. This is a website we have created at LeapWallet so that people can experience the wallet before they actually install it.

**Expected behavior**
Keplr extension does not flag https://cosmos-wallet-demo.web.app/ as a phishing website.

**Screenshots**
<img width="852" alt="image" src="https://user-images.githubusercontent.com/114133109/224936758-6d790fe4-0172-4d74-a576-5b63f4243d83.png">

**Device details:**
 - OS: Windows
 - Browser: Chrome
 - Keplr Version: 0.11.45
 - Hardware Wallet: Not Applicable

**Comment by siddharth-leap** [comment]
@Thunnini could you please take a look at this issue and help resolve it?

**Comment by ctrl-Felix** [comment]
We accidentally blocked all web.app subdomains 2 days ago as subdomains itself aren't supported yet. But that has been fixed so this issue should be fixed too.
I checked it and I don't see a warning.

And to report issues with the web blocking it might be better to use https://github.com/chainapsis/phishing-block-list/ too. We can react to individual problems much faster there!

**Comment by siddharth-leap** [comment]
Thank you for your prompt response @ctrl-Felix , the issue has been resolved.
