### ISSUE TITLE
facing blank keplr after add solar network with osmosis frontier

### ISSUE THREAD

**Issue by hamidaalami** [chainapsis/keplr-wallet#687]
![Screenshot_21](https://user-images.githubusercontent.com/35276321/225905443-58fdad8e-dc1c-4955-a377-430119ed5e90.png)

**Comment by HeesungB** [comment]
@hamidaalami 
I'm fixing it.
Thank you for the information.

**Comment by hamidaalami** [comment]
> @hamidaalami I'm fixing it. Thank you for the information.

thanks buddy

**Comment by HeesungB** [comment]
@Icfaunu Could you share your Keplr Version?

**Comment by DiezelVH4** [comment]
Same issue with my Keplr extension on Chrome, since 2 days.
I didn't add any new chains, I only selected Meme Network from the chains list and it went blank.
Clearing cache, restarting browser and updating keplr extension did not fix the issue.
Keplr version 0.11.48

**Comment by Icfaunu** [comment]
I'm not sure about ver, I think also 0.11.48.

A solution: I removed the Keplr extension and re installed it (seed phrase again) and now it works. I guess this is too much trouble though.

**Comment by Tanen73** [comment]
I confirm having the same problem and it started 3-4 days ago when i selected Meme Network Chain in Keplr Extension.. Result extension blocked in white page and unable to access my funds in other chains. I hope you will fix this bug and suggest how to restart Keplr extension without disinstalling it. Thanks and best regards.

**Comment by Tanen73** [comment]
is there any update for this issue please?

**Comment by hamidaalami** [comment]
my problem got fix on 11.51
![Uploading Screenshot_3.png…]()

**Comment by HeesungB** [comment]
@Tanen73 Still not working with a blank screen?

**Comment by Tanen73** [comment]
> @Tanen73 Still not working with a blank screen?

Yes unfortunately. My extension was blocked attempting connection with MEME Network chain... When I try to open it, I can see that it tries connection ( I can see the written LOADING) but it became totally white in less than a second.. I must say also tha twith 0.11.48 version I wasn't able to connect my Keplr wallet even by the MEME network site (https://wallet.memenetwork.io) where I couls see the written FAILED; now with 0.11.51 version direct connection in the chain site works correctly and i can see my assets.
Her is a snapshot of what can i see when the extension page is totally white and I select with mouse right key " inspect popup" and the script consolle opens with several error messages...
I Hope to be helpful for your work and that this issue will be soon fixed.
Best Regards
![meme](https://user-images.githubusercontent.com/100285332/228909582-3d5dae15-d363-442c-a25e-123cf3f41d45.jpg)

**Comment by kamal-sutra** [comment]
@Tanen73 Can you try this.
right-click on the white page, hit “inspect”, and run browser.storage.local.set({"store_chain_config/extension_last_view_chain_id":null}) in the “console”. After that, turn on the popup again and if it works, delete the MEME network from the extension or whatever network that is causing this issue. and readd it freshly.

**Comment by Tanen73** [comment]
> 

Thank you so much !!! I tried your suggestion and Keplr- extension opened again regularly, so I removed Meme network  from the chain list .  Isuue FIXED. THANKS SO MUCH @kamal-sutra
