### ISSUE TITLE
Outdated Firefox extension

### ISSUE THREAD

**Issue by nesbocaj** [chainapsis/keplr-wallet#690]
**Describe the bug**
The [Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/keplr/) seems to be stuck at [version 0.11.29](https://addons.mozilla.org/en-US/firefox/addon/keplr/versions/), is this intended and if so, why?

**To Reproduce**
1. Go to "https://addons.mozilla.org/en-US/firefox/addon/keplr/"
2. Scroll down to "Version History"
3. Click on "[See all versions](https://addons.mozilla.org/en-US/firefox/addon/keplr/versions/)"
4. See the lack of any version later than [v0.11.29](https://github.com/chainapsis/keplr-wallet/releases/tag/v0.11.29).

**Expected behavior**
I expected so see the availability of the latest version ([v0.11.49](https://github.com/chainapsis/keplr-wallet/releases/tag/v0.11.49)) since a [build for Firefox](https://github.com/chainapsis/keplr-wallet/releases/download/v0.11.49/keplr-extension-v0.11.49.firefox.zip) clearly exists.

**Device details (please complete the following information):**
 - OS: Windows
 - Browser: [Firefox Version 111.0.1 (Release)](https://hg.mozilla.org/releases/mozilla-release/rev/6e9b4327e238def619d5640de74b611fe51834ba)

**Comment by Thunnini** [comment]
It should be fixed by #695
