### ISSUE TITLE
Discussion on signature verify and bech32 address conversion for evm support chain.

### ISSUE THREAD

**Issue by 99Kies** [chainapsis/keplr-wallet#707]
1. The signature obtained by front-end using keplr for evmos failed to verify via python ecdsa under chain.
```python
    # evmos
    sig = {
        "pub_key": {
            "type": "tendermint/PubKeySecp256k1",
            "value": "A49QBDS9TWR4QrruJ5H59NNG+WRQUn3PklKLaIkRrww2"
        },
        "signature": "D7jFyvhUP1BOKla/3xpFShfbHR0YOqdtHeA7S1wfqlISmC4wEt6pBQdZqcEdHhgvhYSID355otY0+EbzAyGzzQ=="
    }

    message = "hello"

    encoded_data = base64.b64encode(message.encode(encoding="utf-8"))

    pub = base64.b64decode(sig['pub_key']['value'])

    p = PublicKey(pub)
    signature_raw = base64.b64decode(sig['signature'])
    msg = {
        "chain_id": "",
        "account_number": "0",
        "sequence": "0",
        "fee": {
            "gas": "0",
            "amount": [],
        },
        "msgs": [
            {
                "type": "sign/MsgSignData",
                "value": {
                    "signer": "evmos1mr4ajt2a6syhjlks06uu6n9ryhwayr60xh5es6",
                    "data": str(encoded_data)[2:-1],
                },
            },
        ],
        "memo": "",
    }

    message_str = json.dumps(msg, separators=(",", ":"), sort_keys=True)
    message_bytes = message_str.encode("utf-8")
    res = p.verify(message_bytes, signature_raw) # False, but use cosmos signature will be `True`
```

2. evm supported chains (such as evmos), when converting bech32 address by public key under the chain, the result of the conversion is different from the address in the wallet.
```python
def pubkey_to_eth_address(pubkey: bytes, *, hrp: str = None) -> str:
    k = keccak_256(pubkey).digest()[-20:].hex()
    if not hrp:
        return "0x" + k

    array = binascii.unhexlify(k)
    words = [x for x in array]
    bech32_words = bech32.convertbits(words, 8, 5)
    bech32_address = bech32.bech32_encode(hrp, bech32_words)
    return bech32_address
```
Does keplr have any pre-processing for the bech32 address of evm support, which can cause uncertainty and confusion for some back-end developers.

**Comment by Thunnini** [comment]
This is the part I'm concerning about as well. It was not initially assumed that there would exist chains with different ways of generating addresses from public keys.
It could be modified to return an additional field like "address generation method" for this part.

**Comment by 99Kies** [comment]
@Thunnini  hi, Is there any relevant code, I did not turn up the specific implementation process. (Looking forward to writing in the dev docs after here to facilitate debugging by back-end developers).

**Comment by 99Kies** [comment]
![image](https://user-images.githubusercontent.com/45918704/230701703-3cb5bbe2-3da5-4e74-8c1e-7625f19d7e40.png)
I found that I did do some manipulation of the `key` of the `evm support chain` during the signature check, can this part be explained? I would like to implement this verify locally in python.

**Comment by Thunnini** [comment]
Just to clarify, that was the intention, but is not something we are currently working on right now. We may revisit once our short term priority tasks are complete.

**Comment by 99Kies** [comment]
@Thunnini  Can you help me with a question first, what is the difference between calling signArbitrary/verifyArbitrary under evmos chainid and calling it under cosmos chainid?

**Comment by 99Kies** [comment]
cosmos use sha3_256 to encode msg, evmos use keccak_256
