### ISSUE TITLE
[QUERY] Setting Fee for particular transactions separately

### ISSUE THREAD

**Issue by arnabghose997** [chainapsis/keplr-wallet#717]
We can set the general Gas Price option through `suggestChainExperimental` through one of the following fields :

```
gasPriceStep: { low: 0.01, avergage: 0.025, high: 0.04 } }
```

This essential applicable to all Transactions of a blockchain transactions. Does Keplr provides the functionality which allows to set different fee for specific Transactions? So, that once the user tries to perform those specific transactions, the fee options being displayed in UI will be different from the usual one.

**Comment by delivan** [comment]
To set a different fee for each tx, simply pass a different gas when passing the fee to the API that signs or broadcasts tx.
```js
...
const fee = {
  amount: [
    {
       denom: "uosmo",
       // this is ignored if `preferNoSetFee` is not true in `KeplrSignOptions`(ref: https://docs.keplr.app/api/#interaction-options)
       amount: "5000",
    },
  ],
  // you can set this conditionally by tx
  gas: "200000",
};
...
```
the fee is calculated for each `gasPriceStep` passed in `suggestChainExperimental`. so it allow the user to choose fee by options. (ex. low fee = gas * gasPriceStep.low)

**Comment by arnabghose997** [comment]
@delivan Thanks for your help.
