### ISSUE TITLE
Support Ledger EIP712 for ExperimentalSuggestChain

### ISSUE THREAD

**Issue by trevormil** [chainapsis/keplr-wallet#720]
Would it be possible to add an option to get access to Ledger Keplr EIP712 for the experimentalSuggestChain feature?

 I am building a custom chain according to Ethermint spec, but there is no way for me to support Keplr Ledger currently. 

Maybe something like this can be an optional feature?
```ts
const KeplrSuggestChainInfo = {
    chainId: "...",
    chainName: "...",
    ....
    features: ["eth-address-gen", "eth-key-sign", "ledger-eip712"],
}
```

From the code, it seems this is explicitly blocked, unless chain is EVMOS or Injective.
[https://github.com/chainapsis/keplr-wallet/blob/master/packages/background/src/keyring/keyring.ts#L1525](https://github.com/chainapsis/keplr-wallet/blob/master/packages/background/src/keyring/keyring.ts#L1525)

```ts
// XXX: There are other way to handle tx with ethermint on ledger.
//      However, some chains have probably competitive spirit with evmos.
//      They make unnecessary and silly minor changes to ethermint spec.
//      Thus, there is a probability that it will potentially not work on other chains and they blame us.
//      So, block them explicitly for now.
public throwErrorIfEthermintWithLedgerButNotSupported(chainId: string) {
    if (this.keyStore && this.keyStore.type === "ledger") {
        if (!chainId.startsWith("evmos_") && !chainId.startsWith("injective")) {
            throw new KeplrError(
                "keyring",
                152,
                "Ledger is unsupported for this chain"
            );
        }
    }
}
```

**Comment by chismo950** [comment]
If your chain id starts with "evmos_", that works, but I wonder if is it legal to use this kind of chain id? I hope the official team answer this question.
