### ISSUE TITLE
Keplr wallet

### ISSUE THREAD

**Issue by toineline** [chainapsis/keplr-wallet#722]
Came after my first problem with Kepler ever.

Was going from one wallet to next for staking maintenance and when I tried to go onto Galaxy Wallet, my Keplr wallet screen has gone blank and cannot get out of it. I actually cannot work out how to close the wallet and have not idea what to do which is frustrating.
a hard logoff function or instruction for any similar recuring event could be a good feature... may it exist but not aware of it  ?
Regards to the team

**Comment by Thunnini** [comment]
I am not familiar with Galaxy wallet, but I assume that issue happened when you selected a suggested chain.
Suggested chains are fully out of control of Keplr, and it's possible that a completely wrong response was returned from that chain's endpoint. 
In the long term, we have plans to build something like a recovery mode, but if you wish to solve it right now,
For now, try right-click on the white page, hit “inspect”, and run browser.storage.local.set({"store_chain_config/extension_last_view_chain_id":null}) in the “console”. After that, turn on the popup again and if it works, delete that chain.

**Comment by toineline** [comment]
Very greatful
Wanted to say thank you.....it did work !!!
Very impressed you took that time. Thank you again will support kepler even more 

Sent from Yahoo Mail on Android 
 
  On Tue, 9 May 2023 at 4:42 pm, JungHwan Tony ***@***.***> wrote:   


I am not familiar with Galaxy wallet, but I assume that issue happened when you selected a suggested chain.
Suggested chains are fully out of control of Keplr, and it's possible that a completely wrong response was returned from that chain's endpoint.
In the long term, we have plans to build something like a recovery mode, but if you wish to solve it right now,
For now, try right-click on the white page, hit “inspect”, and run browser.storage.local.set({"store_chain_config/extension_last_view_chain_id":null}) in the “console”. After that, turn on the popup again and if it works, delete that chain.
