### ISSUE TITLE
IBC coin registered via EVMOS doesn't show up

### ISSUE THREAD

**Issue by vrde** [chainapsis/keplr-wallet#724]
**Describe the bug**
Newly registered IBC coin in EVMOS doesn't show up in my Keplr wallet.

We recently registered an ERC-20 token as an IBC coin (see [proposal 144](https://atomscan.com/evmos/accounts/evmos13ew4v092n8ch4v8cjc8jnr2ct86rsgels7k4hf)).

I converted the token from its ERC-20 representation to its IBC representation, see this balance https://atomscan.com/evmos/accounts/evmos1lu45nhk3v4dm900rd8x9vsmhjwmt428gk7w9rj
![image](https://user-images.githubusercontent.com/134680/236935217-5efa8d6c-16f1-4cef-b9f8-616adf2708fe.png).

If I open the keplr extension and connect to the EVMOS network, I don't see the token.

We are taking further steps to register the metadata of the coin on mintscan and evmos (mode details here https://github.com/NeokingdomDAO/contracts/issues/38).

**To Reproduce**
1. Receive a NEOK IBC Coin
2. Open keplr, it doesn't show up

**Expected behavior**

I expect the coin to show up in my keplr wallet. As far as I know, keplr is just reading from the bank module and the EVMOS proposal that just passed registers the tokens in the bank module.

**Screenshots**

![image](https://user-images.githubusercontent.com/134680/236936539-0b684196-8dc8-4506-8a7f-3a09932edca9.png)

**Device details (please complete the following information):**
 - OS: Ubuntu GNU/Linux
 - Browser: [Version 1.50.125 Chromium: 112.0.5615.165 (Official Build) (64-bit)](https://brave.com/latest/)
 - Keplr Version: 0.11.59
 - Hardware Wallet: n/a

**Additional context**

**Comment by delivan** [comment]
The feature to show ERC20 tokens is buggy now and has been removed for a while from Keplr Wallet.
We're currently preparing the redesign as Keplr Wallet 2.0, so it's been pushed down the priority list a bit. It will be prioritized after the 2.0 is released.

**Comment by vrde** [comment]
Thanks, NEOK is an ERC20 that can be converted to an IBC coin as you can see here https://atomscan.com/evmos/accounts/evmos1lu45nhk3v4dm900rd8x9vsmhjwmt428gk7w9rj

I'm not sure I understand, we have an IBC coin, not an ERC20 one, how is this bug affecting the IBC representation of the token?

**Comment by vrde** [comment]
@delivan any update on this?

**Comment by sirnicolaz** [comment]
@delivan any update on this? I am also quite interested, as we are having issues with this

**Comment by vrde** [comment]
If I transfer NEOK from EVMOS to Crescent using an IBC transfer, I see it under my Crescent account.

![image](https://github.com/chainapsis/keplr-wallet/assets/134680/ec7b1bec-20c2-41a8-b0f1-0c3b497796ee)

I still don't see my NEOK when Keplr is connected to the EVMOS network.
