### ISSUE TITLE
Chrome Addon Crash Selecting Galaxy

### ISSUE THREAD

**Issue by Cstannahill** [chainapsis/keplr-wallet#734]
The app is running into an error when selecting galaxy. I believe they stopped developing, does something not exist that it is checking for in the code that would have previously been there for this chain?

I will attach the console with the error, its trying to read the length of a variable that isn't there. I'm fairly certain just adding optional chaining operators would remedy the situation in the short term. I apologize as I haven't looked at the code for this project at all, so I am not overly familiar, but somewhere around where it is doing checks when loading the specific currency, it is looking for a length property of a variable that is undefined.

![Screenshot (549)](https://github.com/chainapsis/keplr-wallet/assets/108768211/91ca5b6c-8b2d-4156-9a09-50ec9eb4f8dc)
![Screenshot (550)](https://github.com/chainapsis/keplr-wallet/assets/108768211/995d9185-9b54-44e0-a476-8e2b97d1cc87)

**Comment by Thunnini** [comment]
Since the recovery page was added in 2.0, this issue has been resolved.
