### ISSUE TITLE
Keplr 2.0  Error Connect and unlock your Ledger device

### ISSUE THREAD

**Issue by BB83740** [chainapsis/keplr-wallet#739]
**Describe the bug**
I can't claim staking rewards on any chain because transactions cannot be confirmed :  Error : Connect and unlock your Ledger device.
It was working perfectly fine on previous Keplr Chrome extension. Now it seems Cosmos extension cannot be recognised anumore.

**To Reproduce**
1. Go to 'Claim all' then 'claim' ATOM or do it directly  in Keplr dashboard
2. Click on 'Claim and stake'
3. See error

**Expected behavior**
Normally once it says Cosmos ready on nano X screen, it should work and you should see the transactions to validate

**Screenshots**
![image](https://github.com/chainapsis/keplr-wallet/assets/135341522/9accad26-a27f-4966-9443-41be8e6653f2)

**Device details :
 - Windows 10
 - Browser: Version 114.0.5735.91 (Build officiel) (64 bits)
 - Keplr Version: Keplr 0.12.3
 - Hardware Wallet: Ledger nano X 2.2.1

**Comment by Deploydon** [comment]
Temporary work around is to click Add Wallet --> Connect Hardware Wallet --> Connect Ledger --> Give it any random name. Let it connect / find. Then you can exit and delete that wallet. 

Seems the webusb connection stops working after upgrade, so forcing this will let you other wallets work again.

**Comment by BB83740** [comment]
It did not work either. However I unplugged the device from the usual usb
port to another one and it worked. Seems the upgrade version of kepler
killed the usual webusb connection for some reasons.

**Comment by davepuchyr** [comment]
Error: Failed to init transport
    at 23.bundle.js:851:56220
    at Generator.throw (<anonymous>)
    at s (23.bundle.js:851:53259)

**Comment by davepuchyr** [comment]
Bump.  Fixing this issue is crucial to Ledger users.  If it can't be fixed immediately then please provide a mechanism to rollback to Keplr v1.

**Comment by Thunnini** [comment]
@BB83740 @davepuchyr Let me know that this way can solve your issue.

**Comment by davepuchyr** [comment]
> @BB83740 @davepuchyr Let me know that this way can solve your issue.

Yes!  That worked.  Thank-you, @Thunnini !

The 3 tries trick should be explicitly stated on the first failure to connect. :)

**Comment by Thunnini** [comment]
The author has no answer... but I'm closing the issue as several users have confirmed that they can solve this problem by the above way.
