### ISSUE TITLE
Provide a way to disable analytics

### ISSUE THREAD

**Issue by PFC-developer** [chainapsis/keplr-wallet#745]
provide a way to disable logging of information to analytics services

I'd prefer my wallet not to phone-home and send anything, regardless of how anonymized you claim it to be

**Comment by HeesungB** [comment]
@PFC-developer  Ongoing at this link.

https://github.com/chainapsis/keplr-wallet/pull/753

**Comment by Thunnini** [comment]
This feature is added from v0.12.10
