### ISSUE TITLE
Keplr 2.0 extension window doesn't close automatically when signing message for custom chain

### ISSUE THREAD

**Issue by dillu24** [chainapsis/keplr-wallet#763]
**Describe the bug**

Hey Keplr team,

We are trying to integrate our custom chain with Keplr free version and we have been looking into how to sign custom TXs. At the moment we are getting the offline signer and passing it to cosmJs's `signAndBroadcast` function. When we click the `Approve` button from the Keplr extension, the Keplr 2.0 window doesn't close automatically, however, the TX is passing because we are managing to `console.log` the result. Any idea what might be the issue?

**Expected behavior**

The Keplr 2.0 extension signing window should close when clicking on the `Approve` button.

**Device details (please complete the following information):**
 - OS: 22.04.1-Ubuntu
 - Browser: Chrome Version 114.0.5735.106 (Official Build) (64-bit)
 - Keplr Version: 0.12.9

**Comment by dillu24** [comment]
Window which is not closing automatically:

![image](https://github.com/chainapsis/keplr-wallet/assets/23262259/dc13eba3-c7d5-49dc-b105-d8d2cf0341ab)

**Comment by Thunnini** [comment]
Hi, thank you for reaching out! Tbh, we cannot solve the issue with the info you provided, and we could not reproduce the issue on our end. Please specify 1) if it is occurring consistently or only under certain conditions, 2) browser you're using (seems like you said you're using chrome but the screenshot is on firefox), 3) and a specific example in which we could send the transaction you've mentioned.

**Comment by dillu24** [comment]
1. It is only occurring for our own suggested chain.
2. It is happening on both chrome and firefox.
3. Not sure how this can be done because our chain is not public yet.

**Comment by dillu24** [comment]
Are there any things maybe that we could check from our end to confirm that our implementation was done correctly?

**Comment by Thunnini** [comment]
Does the same happen on Windows or OSX? (Is this only happening in linux?)

**Comment by dillu24** [comment]
Hi, it seems the issue was because we were using a Tendermint34 object on CosmJS to connect with a Cosmos SDK 0.43.7 chain. 

So it has nothing to do with keplr. Still, thanks for your help 🙂

**Comment by Thunnini** [comment]
Thank you for your report.
