### ISSUE TITLE
Dashboard shows incorrect value for AVAX/OSMO pool

### ISSUE THREAD

**Issue by tdiesler** [chainapsis/keplr-wallet#772]
**Describe the bug**

The "Value" that I see for the AVAX/OSMO pool in the Dashboard is 1/2 of what I see on [Osmosis #899](https://app.osmosis.zone/pool/899)

AFAICS, it only happens with AVAX/OSMO (i.e. values for SCRT/OSMO, ATOM/OSMO match)

**Comment by delivan** [comment]
@tdiesler thanks for the report. It's fixed now. please check it out!
