### ISSUE TITLE
The error gas estimate is too high on sei . network

### ISSUE THREAD

**Issue by PThangDev** [chainapsis/keplr-wallet#781]
### I have a gas fee problem when making a transaction on sei . network. It's too high

<img width="361" alt="Screenshot 2023-07-05 at 01 27 19" src="https://github.com/chainapsis/keplr-wallet/assets/103823554/055940c1-381b-4be0-b7b1-c85e1ff6e47a">

**Comment by HeesungB** [comment]
@PThangDev Could you check this link?
https://github.com/chainapsis/keplr-chain-registry/pull/171

```
we will be sending out the proposal after making the gas change because we don't want to break existing integrations by having wallet gas < chain gas. Given that the proposal increases the gas, if we have the proposal pass first, then wallets will fail since they will not require enough gas so we would like to merge this PR soon.

Here's a similar proposal we plan to send out: https://github.com/sei-protocol/testnet/blob/main/atlantic-2/proposals/05-30-2023-increase-min-gas.json
```

**Comment by PThangDev** [comment]
Thanks bro. I hope it will be fixed soon!
