### ISSUE TITLE
IRIS token not accessible on cosmos hub

### ISSUE THREAD

**Issue by Hattrix3** [chainapsis/keplr-wallet#796]
Aspchh@aol.com
With the new keplr extension for chrome
I see the Iris chain
However I had Iris coin on cosmos and only see cosmos 
Not able to switch atom to IRIS on cosmos hub

Help

**Comment by HeesungB** [comment]
@Hattrix3 Hello.
You can see IRIS token when you go `Manage Chain Visibility` and turn on `IRIS` token.

Thank you.
