### ISSUE TITLE
 Shade Protocol Integration

### ISSUE THREAD

**Issue by mohammedpatla** [chainapsis/keplr-wallet#799]
**Is your feature request related to a problem? Please describe.**
The problem is that despite Shade Protocol supporting mobile and being a DeFi application on Secret Network that has supported Keplr since its inception, it is currently not accessible via the Keplr Mobile App. This creates a gap for users who primarily interact with DeFi apps through their mobile devices and prefer the convenience of using a mobile app. This also drives some competitors to come and enable the shade app on their wallet platform.

**Describe the solution you'd like**
The ideal solution would be to integrate access to Shade Protocol directly into the Keplr Mobile App. This would allow users to interact with Shade Protocol and its features directly from their mobile devices through the Keplr app, thus enhancing user experience and boosting the app's functionality. Since Shade Protocol already supports mobile, the integration should be feasible.

**Describe alternatives you've considered**
Another option could be the implementation of a mobile-friendly web interface for Shade Protocol that can be accessed independently of the Keplr app. However, this doesn't offer the same seamless user experience as having everything integrated into one app.

**Additional context**
Shade Protocol is a DeFi application on the Secret Network that has been supporting Keplr from day one. It recently implemented mobile support. This feature request aims to enhance the convenience and user experience of Keplr mobile app users by integrating Shade Protocol into the app. This would allow users to have direct access to Shade Protocol and its functionalities from within the Keplr Mobile App.

In addition to this, we would like to see the SNIP-20 tokens of Shade Protocol - SHD and SILK, visually represented with their respective icons within the Kepler Extension. Having these icons would provide a more intuitive and user-friendly experience, making it easier for users to navigate and manage their assets.

For reference, this is the link to the Shade Protocol platform that we would like to see integrated: https://app.shadeprotocol.io/

**Comment by HeesungB** [comment]
@mohammedpatla Hello.
There are a few features supported by the extension that are not supported on mobile.
Let's take a look at them.

Thank you

**Comment by mohammedpatla** [comment]
This was integrated, thank you!!
