### ISSUE TITLE
Keplr types conflicting with SVG types declaration

### ISSUE THREAD

**Issue by Wgil** [chainapsis/keplr-wallet#811]
**Describe the bug**

I'm building a Dapp using next.js and I have the following declaration to support svg modules:

```ts
declare module '*.svg' {
  /**
   * Use `any` to avoid conflicts with
   * `@svgr/webpack` plugin or
   * `babel-plugin-inline-react-svg` plugin.
   */
  const content: any;

  export default content;
}
```

It seems that if I import `import {Keplr} from '@keplr-wallet/types';` my build on the pipeline starts failing with the following error:

<img width="1078" alt="Screenshot 2023-08-11 at 11 54 01 AM" src="https://github.com/chainapsis/keplr-wallet/assets/12855914/58718103-5794-4ccf-9dd4-60836480a339">

it's worth noting that the error is only replicable on CI. Uninstalling the types package fixes the build.

Node version: v16.19.0

**Comment by HeesungB** [comment]
@Wgil Hello.
Can you try again with the link below?
https://docs.keplr.app/api/#using-with-typescript

**Comment by Wgil** [comment]
@HeesungB Hi,

Gave it another shot and it worked this time. Not sure what happened before.

Thank you
