### ISSUE TITLE
New Denom default rendering in extension appears un-configured 

### ISSUE THREAD

**Issue by r0mille** [chainapsis/keplr-wallet#815]
**Describe the bug**
The balance in the extension for a new denom on a partner ibc chain (Osmosis) by default looks un-configured.

We'd like to understand how we can update any configuration so that this denom appears well-formed.

Why we care about the bug: we discovered this because we are trying to add USDT to Kava's Chain configuration and trying to sort out the proper way to add that and during this investigation we discovered that the denom was already being detected by Keplr but is displaying with wrong information.

**To Reproduce**
This may be difficult because it may be specific to this denom / specific configs. In this case the denom is on the Osmosis chain, but here are the steps on our end to reproduce.

1. Open extension
2. View more tokens
3. Scroll until you see the denom you're looking for.

**Expected behavior**
The display name should be "USDt" - see screenshot. The microdenom should be "erc20/tether/usdt". If you were going to query the KAVA chain for balances then "erc20/tether/usdt" would be the identifier you'd use. 

Additionally the conversion / decimal factor seems incorrect (or is not being applied) as well and it would be great to be able to define the icon / logo. 

**Screenshots**
<img width="364" alt="Screenshot 2023-08-18 at 1 45 12 PM" src="https://github.com/chainapsis/keplr-wallet/assets/2582481/e59b06bf-0257-4cd8-97da-2ef9d634318f">

**Device details (please complete the following information):**
 - OS: OS X
 - Browser: Chrome 114.0.5735.198
 - Keplr Version: 0.12.20

Happy to provide any additional information that I'm missing here. Thanks in advance. 
cc: @downing034

**Comment by Thunnini** [comment]
Is it correct that "erc20/tether/usdt" exists as `sdk.Coin` on the chain's bank module? If so, https://github.com/chainapsis/keplr-chain-registry/blob/main/cosmos/kava_2222.json put your PR here.

**Comment by Thunnini** [comment]
@r0mille The information embedded in the extension is currently only used as an initial value. Put PR only to keplr-chain-registry because if the user's network is normal, chain info is updated from keplr-chain-registry.

**Comment by r0mille** [comment]
Thanks for the explanation @Thunnini 
Submitted the PR https://github.com/chainapsis/keplr-chain-registry/pull/218. 

And so once it's merged in, you would expect this issue to be resolved?

**Comment by r0mille** [comment]
Closed since https://github.com/chainapsis/keplr-chain-registry/pull/218 was merged. Thanks
