### ISSUE TITLE
upgrade android to sdk level 33

### ISSUE THREAD

**Issue by solitarysp** [chainapsis/keplr-wallet#819]
By September, google will be required to upgrade the application using sdk 33. Do we have a plan to do this?

**Comment by HeesungB** [comment]
@solitarysp Yes We will update android targetSdkVersion to 33

**Comment by solitarysp** [comment]
Thanks, it would be great if you could show me that PR when it's created

**Comment by HeesungB** [comment]
@solitarysp You can check this commit.
https://github.com/chainapsis/keplr-wallet/commit/44968e0661f8e4b7c46bb24bf007581557f4b5a1

**Comment by lethanh9398** [comment]
@HeesungB could you help me close issue?

**Comment by HeesungB** [comment]
@solitarysp Could you tell me about your issue?

**Comment by solitarysp** [comment]
@HeesungB The issue has been resolved, thank you very much.
