### ISSUE TITLE
Wallet connections

### ISSUE THREAD

**Issue by LL-Cosmo** [chainapsis/keplr-wallet#850]
![IMG_20231005_221402](https://github.com/chainapsis/keplr-wallet/assets/79336608/bd391223-1ee1-4cb9-b2f3-74d93ae0026d)

**Manage connections**

- Trash symbol is out of sight on the right corner of the screen if the connection link is long. This prevents from deleting connections.

- Phone screen size 6.7"

**Comment by HeesungB** [comment]
@LL-Cosmo Hello. I fixed it. It will be reflected!
#854
