### ISSUE TITLE
List of Events

### ISSUE THREAD

**Issue by dillu24** [chainapsis/keplr-wallet#868]
Is there a list of events that Keplr emits on desktop?

I am in particular looking for events that are emitted whenever a user signs a transaction.

**Comment by HeesungB** [comment]
Currently, the evnet we support only supports keychange.
https://docs.keplr.app/api/#change-key-store-event

You need to use Cosmos-kit or implement it with websocket.

**Comment by dillu24** [comment]
Agreed
