### ISSUE TITLE
Show Active Stakes in Kepler Dashboard

### ISSUE THREAD

**Issue by blueyetisoftware-jason** [chainapsis/keplr-wallet#92]
Instead of showing empty staking dashboards (https://wallet.keplr.app/#/dashboard) for Cosmos, Kava and Secret, I would like to show the tokens that are actually held in my Kepler wallet. For example, if I hold Certik or Starname then those would appear on the dashboard instead. A dynamic dashboard would be nice as more tokens are added in the future.

<img width="1410" alt="Screen Shot 2021-05-16 at 11 02 07 PM" src="https://user-images.githubusercontent.com/16869740/118445755-4fcdb700-b69b-11eb-84d0-30a7e359f3d2.png">

**Comment by Harry-1976** [comment]
This, or as an alternative display the chains in the dashboard that we marked as Favorite.
