### ISSUE TITLE
Default gas is too low for IBC Transfer, and no error is raised

### ISSUE THREAD

**Issue by ebuchman** [chainapsis/keplr-wallet#99]
The default gas in Keplr for IBC Transfers is 120000. 

This might work initially, but eventually it's too little.

I was finding myself sending IBC Transfers through Keplr and everything looked like it worked but then the coins didn't leave the account. Eventually I realized the gas was too low. 

So there's two issues here:

1. Set the default gas higher for IBC Transfers (I've just been using 300000)
2. Return some kind of error to the user if the gas is too low

**Comment by arno01** [comment]
yep, I'm already having to raise them manually, sometimes up to 400000, even had to go 600000 and 700000 today.
